### ISSUE TITLE
Error in registered()[[bpparamClass]] :    attempt to select less than one element in get1index

### ISSUE THREAD

**Issue by ShixiangWang** [GuangchuangYu/clusterProfiler#100]
Y叔您好，

我在使用clusterProfiler做GSEA时碰到如题报错。我参考[R包说明文档](http://www.bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html#go-gene-set-enrichment-analysis)做的。
```
> genelist <- final.sig$logFC  # final.sig是用limma包处理后提出的显著子集
> names(genelist) <- rownames(final.sig)
> genelist <- sort(genelist, decreasing = TRUE)
> library(org.Hs.eg.db)
> ego2 <- gseGO(geneList     = genelist,
+               OrgDb        = org.Hs.eg.db,
+               ont          = "MF",
+               nPerm        = 1000,
+               minGSSize    = 100,
+               maxGSSize    = 500,
+               pvalueCutoff = 0.05,
+               verbose      = FALSE)
Error in registered()[[bpparamClass]] : 
  attempt to select less than one element in get1index
```

之前看您博客里写过只要设定好`geneList`就能愉快地使用GESA了，我自己觉得这里的genelist应该没什么问题，您看看是不是有什么不对的？
```
> length(genelist)
[1] 2733
> head(genelist)
   SFTA2    MUC5B    HNF1B     MSLN      PGC   SPINK1 
4.854245 4.700606 4.579293 4.497992 4.465890 4.428753 
> head(final.sig)
          logFC   AveExpr        t      P.Value    adj.P.Val         B
SFTA2  4.854245 4.1072038 17.57650 2.336357e-54 2.498198e-52 112.90704
MUC5B  4.700606 3.0311258 13.79439 5.513979e-37 1.280566e-35  73.16582
HNF1B  4.579293 0.5560836 20.06553 2.319076e-66 1.376028e-63 140.38184
MSLN   4.497992 2.4479547 14.90706 6.122885e-42 2.116209e-40  84.49396
PGC    4.465890 5.2951511 11.99091 2.433323e-29 3.255153e-28  55.70252
SPINK1 4.428753 2.0467598 13.87347 2.481608e-37 5.903523e-36  73.95839
```

我参考过洲更同学的[富集分析](http://mp.weixin.qq.com/s?__biz=MzI1MjU5MjMzNA==&mid=2247484528&idx=1&sn=3af297d4163a70b049f861fc28c85bc2&chksm=e9e02dd1de97a4c79ab04a2c012ee6fe4b0aae5e1df59bdf2bf6b19e6ac1cb08ce379a6694e8&scene=21#wechat_redirect)。 里面在参数设定中有`keytype`键的设置，所以我尝试了下在`gseGO`函数里设定`keytype='ALIAS'`，然而还是一样的错误。

我有点不懂它具体的原理，所以现在不知道从哪方面去解决，如果您知道怎么解决的话请指点下。谢谢！

按照您的发布issue的要求，我创造了一个样例
```
> library(clusterProfiler)
> library(org.Hs.eg.db)
> genelist <- structure(c(4.85424488188991, 4.70060610235887, 4.5792925196846, 
+ 4.49799232283436, 4.46589035431595, 4.42875314960716, 4.39711535432459, 
+ 4.34857795275504, 4.30134940946992, 4.23985866141625), .Names = c("SFTA2", 
+ "MUC5B", "HNF1B", "MSLN", "PGC", "SPINK1", "SFTA3", "CAPN8", 
+ "NAPSA", "TESC"))
> ego2 <- gseGO(geneList     = genelist,
+               OrgDb        = org.Hs.eg.db,
+               ont          = "MF",
+               nPerm        = 1000,
+               minGSSize    = 10,
+               maxGSSize    = 500,
+               pvalueCutoff = 0.05,
+               verbose      = FALSE)
Error in registered()[[bpparamClass]] : 
  attempt to select less than one element in get1index
```
`genelist`就直接提取的前十个。
```
> dput(genelist[1:10])
structure(c(4.85424488188991, 4.70060610235887, 4.5792925196846, 
4.49799232283436, 4.46589035431595, 4.42875314960716, 4.39711535432459, 
4.34857795275504, 4.30134940946992, 4.23985866141625), .Names = c("SFTA2", 
"MUC5B", "HNF1B", "MSLN", "PGC", "SPINK1", "SFTA3", "CAPN8", 
"NAPSA", "TESC"))
```

**Comment by GuangchuangYu** [comment]
试一下`keytype='SYMBOL'`.

**Comment by ShixiangWang** [comment]
不好意思，忘记关掉了~

**Comment by muhammed-ali** [comment]
Dear Guangchuang Yu,
I was trying to do the same thing and I am getting the above mentioned error, even if I define the `keyType`
For simplicity, I will consider only the example used in this [tutorial](http://www.bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html#go-analysis):
library(clusterProfiler)
library(org.Hs.eg.db)
data(geneList, package="DOSE")
length(geneList)
#[1] 12495
head(geneList)
#    4312     8318    10874    55143    55388      991 
# 4.572613 4.514594 4.418218 4.144075 3.876258 3.677857
ego3 <- gseGO(geneList = geneList, OrgDb = org.Hs.eg.db, nPerm = 1000, minGSSize = 100, maxGSSize = 500, pvalueCutoff = 0.05, verbose = T)
# preparing geneSet collections...
# GSEA analysis...
# Error in registered()[[bpparamClass]] : 
#  attempt to select less than one element in get1index

ego3 <- gseGO(geneList = geneList, OrgDb = org.Hs.eg.db, keyType = 'ENTREZID', nPerm = 1000, minGSSize = 100, maxGSSize = 500, pvalueCutoff = 0.05, verbose = T)
# preparing geneSet collections...
# GSEA analysis...
# Error in registered()[[bpparamClass]] : 
#  attempt to select less than one element in get1index

Can you please suggest me what am I doing wrong here? Thank you.

**Comment by muhammed-ali** [comment]
I think there was some problem with existing packages like "BiocParallel". When I updated all the packages, it resolved my problem. I am able to go ahead with your guide. Please ignore the above post. Thanks.

**Comment by GuangchuangYu** [comment]
@muhammed-ali thanks for your update.
