### ISSUE TITLE
enrichPathway fails with error ‘'package' must be of length 1’

### ISSUE THREAD

**Issue by yesitsjess** [GuangchuangYu/clusterProfiler#101]
`test <- c("1", "100", "1000", "10000")`
`enrichPathway(test, organism='hsa', pvalueCutoff=0.05)`

> character(0)
> Failed with error:  ‘'package' must be of length 1’

clusterProfiler_3.5.5
ReactomePA_1.18.1

**Comment by GuangchuangYu** [comment]
You should use `organism="human"`.

I will allow `enrichPathway` to accept `organism="hsa"` either in future release.
