### ISSUE TITLE
The parameter of “ont, One of "MF", "BP", and "CC" subontologies.”  in the function “groupGO ()” Couldn’t work 

### ISSUE THREAD

**Issue by zyb1984** [GuangchuangYu/clusterProfiler#105]
Example :
  Follow the code on http://www.bioconductor.org/packages/devel/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html 
>    library("clusterProfiler") 
>    data(geneList, package="DOSE")
>   gene <- names(geneList)[abs(geneList) > 2]
>   gene.df <- bitr(gene, fromType = "ENTREZID", toType = c("ENSEMBL", "SYMBOL"),
    OrgDb = org.Hs.eg.db)
>   head(gene.df)

## 6      991 ENSG00000117399  CDC20

>   ggo <- groupGO(gene=gene, OrgDb = org.Hs.eg.db, Ont = "CC", level = 2, 
readable = TRUE)
>   head(ggo)

   I also try the parameter of Ont = "MF" to Ont = "BP" and Ont = "CC", but it also don’t work, and with 
 
But try the code on http://127.0.0.1:31164/library/clusterProfiler/html/groupGO.html, it can work.
>    data(gcSample)
>    yy <- groupGO(gcSample[[1]], 'org.Hs.eg.db', ont="BP", level=2)
>    head(summary(yy))

**Comment by GuangchuangYu** [comment]
>I also try the parameter of Ont = "MF" to Ont = "BP" and **Ont** = "CC", but it also don’t work, and with
>
>But try the code on http://127.0.0.1:31164/library/clusterProfiler/html/groupGO.html, it can work.
>
>    data(gcSample)
>    yy <- groupGO(gcSample[[1]], 'org.Hs.eg.db', **ont**="BP", level=2)

wrong spelling.
