### ISSUE TITLE
couldn’t  support the keytype  in  'ENSEMBL' in the function “enrichGO” 

### ISSUE THREAD

**Issue by zyb1984** [GuangchuangYu/clusterProfiler#106]
>   ego2 <- enrichGO(gene=gene.df$ENSEMBL, OrgDb=org.Hs.eg.db, 
+  keytype = 'ENSEMBL', ont = "CC", pAdjustMethod = "BH", pvalueCutoff  = 0.01,
+   qvalueCutoff  = 0.05)
##   参数没有用(keytype = "ENSEMBL")
>  ego2 <- enrichGO(gene=gene.df$ENSEMBL, OrgDb=org.Hs.eg.db, 
+  ont = "CC", pAdjustMethod = "BH", pvalueCutoff  = 0.01,
+ qvalueCutoff  = 0.05)
##  --> return NULL.
>   head(ego2)
NULL

**Comment by GuangchuangYu** [comment]
the answer was already in the welcome message, <https://github.com/GuangchuangYu/clusterProfiler/issues/new>, and you just ignore it.

Your question will also be ignored.
