### ISSUE TITLE
The parameter of “ listType = "Gene" ”in the function “enrichDAVID” Couldn’t work

### ISSUE THREAD

**Issue by zyb1984** [GuangchuangYu/clusterProfiler#107]
>   david <- enrichDAVID(gene = gene, idType = "ENTREZ_GENE_ID",
+  listType = "Gene", annotation = "KEGG_PATHWAY", 
+  david.user = "clusterProfiler@hku.hk")
## Error in enrichDAVID(gene = gene, idType = "ENTREZ_GENE_ID", listType = "Gene",  :  参数没有用(listType = "Gene")
The query results from “http://127.0.0.1:26165/library/clusterProfiler/html/enrichDAVID.html ” , I find the function become this “enrichDAVID(gene, idType = "ENTREZ_GENE_ID", universe, minGSSize = 10, maxGSSize = 500, annotation = "GOTERM_BP_FAT", pvalueCutoff = 0.05, pAdjustMethod = "BH", qvalueCutoff = 0.2, species = NA, david.user), so I run this modified code like this 
>   david <- enrichDAVID(gene = gene, idType = "ENTREZ_GENE_ID",
+  universe = "Gene", annotation = "KEGG_PATHWAY", 
+  david.user = "clusterProfiler@hku.hk")
 And it also don’t work,.
Error in .jcall(stub, "S", "authenticate", email) : 
  org.apache.axis2.AxisFault: david.ncifcrf.gov

**Comment by GuangchuangYu** [comment]
same as <https://github.com/GuangchuangYu/clusterProfiler/issues/106>.
