### ISSUE TITLE
Confuseable keyType for enrichKEGG and setReadable

### ISSUE THREAD

**Issue by Tong-Chen** [GuangchuangYu/clusterProfiler#108]
### Prerequisites

+ [ * ] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ * ] make sure your are using the latest release version
	* [ * ] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [ * ] google your quesion/issue

### Confuseable keyType for enrichKEGG and setReadable

Running the following code

```
library(org.Hs.eg.db)
data(geneList)
de <- names(geneList)[geneList > 1]
kk <- enrichKEGG(de, organism="hsa", pvalueCutoff=0.05, pAdjustMethod="BH",
qvalueCutoff=0.1)
kk2 <- setReadable(kk, OrgDb = org.Hs.eg.db)
```

well generate `keytype` error

```
Error in EXTID2NAME(OrgDb, genes, keytype) : keytype is not supported...
```

which can be solved after multiple tries using 

```
kk2 <- setReadable(kk, OrgDb = org.Hs.eg.db, keytype="ENTREZID")
```

But there are two issues,

1. When leaving `keytype` parameter in `setReadable` default as `auto`, it will try to get `keyType` from enrichment result using `kk2@keytype`, which default value `kegg` is unsupported by `setReadable`. Can `auto` be more intelligent to decide id type?

2. Try another way of running `enrichKEGG`, explicitly set keyType as `ENTREZID` is unsupported. Actually, in KEGG database, `KEGG id` and `ENTREZID` is the same. Is there any way to support this keyType to make setReadable feasibly?

```
> kk <- enrichKEGG(de, organism="hsa", pvalueCutoff=0.05, pAdjustMethod="BH", 
+                  qvalueCutoff=0.1, keyType="ENTREZID")
Error in KEGG_convert("kegg", keyType, species) : 
  ENTREZID is not supported for hsa ...
```

Thanks!

Chen Tong

**Comment by GuangchuangYu** [comment]
>    When leaving keytype parameter in setReadable default as auto, it will try to get keyType from enrichment result using kk2@keytype, which default value kegg is unsupported by setReadable. Can auto be more intelligent to decide id type?

`keyType='auto' ` is expected to work with `enrichGO` output, but no `enrichKEGG`.  I will update the souce code to throw friendly msg.

 >   Try another way of running enrichKEGG, explicitly set keyType as ENTREZID is unsupported. Actually, in KEGG database, KEGG id and ENTREZID is the same. Is there any way to support this keyType to make setReadable feasibly?

KEGG id and ENTREZID are the same for only some of the species, but not always the same.

Sorry for the `keyType` is not consistent between `enrichKEGG` and `setReadable`.  I can do nothing about it since `enrichKEGG` using `KEGG` database while `setReadable` using `OrgDb`.

**Comment by MubasherMohammed** [comment]
@GuangchuangYu Thank you for infos! 
I am working with org.Pf.plasmo.db in cluster profiler and I have issues with keytypes it gives me error as in the screenshot, I couldn't figure it out, any help would be great!
<img width="829" alt="Screenshot 2020-05-11 at 19 09 18" src="https://user-images.githubusercontent.com/50444056/81590507-2f4d8b80-93bb-11ea-8d07-1462945fbbe7.png">

**Comment by Rohit-Satyam** [comment]
Hi @MubasherMohammed 

Were you able to figure this out

**Comment by MubasherMohammed** [comment]
> Hi @MubasherMohammed
> 
> Were you able to figure this out
@Rohit-Satyam  yes you can use "ALIAS" for org.Pf.plasmo.db, only you should have acc number for you gene list.

cheers

**Comment by suburbianmantia** [comment]
Hope this is not too late but one trick could be to modify the output of enrichKEGG and replace ENTREZIDs with gene names. 

Here is a reprex, but I am not sure this is what you were looking for. Hope this will be useful for some people : 

```
library(clusterProfiler)
library(DOSE)
library(dplyr)
library(org.Hs.eg.db)
data("geneList")

degs_entrez = names(geneList[geneList > 2|geneList<(-2)])
full_entrez = names(geneList)

#build a conversion table from ENTREZ to SYMBOL

conversion_table = bitr(full_entrez, 
                        OrgDb = org.Hs.eg.db, 
                        fromType = "ENTREZID", 
                        toType = "SYMBOL")

#create the enrichKegg object
enrich_k = enrichKEGG(gene = degs_entrez,
                      universe = full_entrez,
                      organism = 'hsa')

cnetplot(enrich_k)
```

Here is the output you're getting from cnetplot : 
![Rplot](https://github.com/YuLab-SMU/clusterProfiler/assets/74857304/00ef9b10-3e54-4404-8309-51950eaff358)

```
#function to convert entrezids to gene name
convert_entrezid_to_genename <- function(entrezid_list, conversion_table) {
  entrezid_vec <- unlist(strsplit(entrezid_list, "/"))
  gene_names <- conversion_table$SYMBOL[match(entrezid_vec, conversion_table$ENTREZID)]
  return(paste(gene_names, collapse = "/"))
}

#extract the dataframe from enrichKEGG object
temp_df = enrich_k@result

#replace the IDs with sapply
temp_df$geneID = sapply(temp_df$geneID, convert_entrezid_to_genename, conversion_table = conversion_table)

#modify the result table
enrich_k@result = temp_df

#here you go
cnetplot(enrich_k)
```

![Rplot012](https://github.com/YuLab-SMU/clusterProfiler/assets/74857304/a6acedf7-e451-4055-818f-0cb2a678a933)

It was useful for me, but if irrelevant, please feel free to remove it.

Cheers!
