### ISSUE TITLE
Error in compareCluster - enrichDAVID

### ISSUE THREAD

**Issue by adomingues** [GuangchuangYu/clusterProfiler#11]
When using enrichDAVID in compareCluster, if none of the gene sets retrieves signicant enrichment from the tested category, there is a fairly obsocure error:

> Error in if (pi0 <= 0) { : missing value where TRUE/FALSE needed
> In addition: Warning messages:
> 1: In min(p) : no non-missing arguments to min; returning Inf
> 2: In max(p) : no non-missing arguments to max; returning -Inf

I ran a few tests until figuring that is the problem. The ouptut of `x <- getFunctionalAnnotationChart(david, threshold=1, count=minGSSize)` will be:
> DAVID Result object
> Result type:  FunctionalAnnotationChart 
> data frame with 0 columns and 0 rows
For all elements of `gene`. I am posting it here so that other users will know what the issue is.

**Comment by GuangchuangYu** [comment]
Thanks for your feedback.

I have updated the source code of enrichDAVID, https://github.com/GuangchuangYu/clusterProfiler/commit/0a9e90b4618680dd2b07a30a8d0c5236467c5e38

So that if this case happened, it will throw warning message and return NULL.

**Comment by GuangchuangYu** [comment]
I guess this may happen very often, for user may pass the wrong idType and all gene will be unmapped and no result return.

**Comment by adomingues** [comment]
Cheers. It is quite possible, but at least now there is meaningful warning to quickly identify the source of the problem.

**Comment by GuangchuangYu** [comment]
If it is due to wrong idType, enrichDAVID will throw stop msg for it. https://github.com/GuangchuangYu/clusterProfiler/commit/ac098f7a1118e296a5e73d90aec9afa984d9edbb
