### ISSUE TITLE
Plotting in PDF format fails

### ISSUE THREAD

**Issue by infB** [GuangchuangYu/clusterProfiler#112]
Hi Guangchuang,
I am using clusterProfiler for GO and KEGG analysis. Plotting the result of your barplot()-function into a pdf file, fails. Text and axis description are not plotted correct:

`pdf("ego.pdf", w=1000, h=500)`
`barplot(ego, drop=TRUE, showCategory=12)`
`dev.off()`

![barplot_ggo](https://user-images.githubusercontent.com/13436818/32367189-906f8d24-c081-11e7-8ca5-89577b10fd6f.png)

Plotting the same data into an png file works:

`png("ego.png", w=1000, h=500)`
`barplot(ego, drop=TRUE, showCategory=12)`
`dev.off()`

![go_classification_down_regulated_bp_barplot](https://user-images.githubusercontent.com/13436818/32367264-de23f6fe-c081-11e7-8a7f-f8c7a446d84e.png)

Unfortunately I could not add an title to the plot or resize the font. Do you have a solution for my Problems?

Thanks a lot!

**Comment by GuangchuangYu** [comment]
for exporting the figure to file, I recommend you use `ggsave()`.

For customization, e.g. add title, resize font *etc.*, you need to learn `ggplot2`.

**Comment by infB** [comment]
Thank you for you fast answer. I must have overlooked the information about ggplot2. Now all works fine!

Thank you!
