### ISSUE TITLE
ID recognition error

### ISSUE THREAD

**Issue by snoopy-448** [GuangchuangYu/clusterProfiler#115]
Hi Guangchuang,
I am using clusterprofiler for GO and KEGG over representation analysis. My input is a list of ensembl gene ids.(attached in gene_list.txt).
[gene_list.txt](https://github.com/GuangchuangYu/clusterProfiler/files/1449715/gene_list.txt)

But when I run:
`library(clusterProfiler)`
`library(org.Hs.eg.db) `
`input_file <- 'F:\\gaoqiang_immune\\gene_list.txt'`
`input_ids <- scan(input_file, what = character(0))`
```
go_enrich <- enrichGO(gene = input_ids,
                      OrgDb = org.Hs.eg.db,
                      keytype = 'ENSEMBL',
                      ont = 'BP',
                      pAdjustMethod = 'BH',
                      pvalueCutoff = 0.01,
                      qvalueCutoff = 0.05,
                      readable = TRUE)
```
`head(go_enrich)`
, it returns:
`[1] ID          Description GeneRatio   BgRatio     pvalue      p.adjust    qvalue      Count      
<0 行> (或0-长度的row.names)`
However, when I first transform my ensembl ids to entrez ids using bitr, and used the entrez ids to run enrichgo, like this:
`new_ids <- bitr(input_ids, fromType = 'ENSEMBL', toType = c('SYMBOL', 'ENTREZID'), OrgDb = 'org.Hs.eg.db')`
```
go_enrich <- enrichGO(gene = new_ids$ENTREZID,
                      OrgDb = org.Hs.eg.db,
                      keytype = 'ENTREZID',
                      ont = 'BP',
                      pAdjustMethod = 'BH',
                      pvalueCutoff = 0.01,
                      qvalueCutoff = 0.05,
                      readable = TRUE)
```
`head(go_enrich)`
It will show me the reasonable result. I cannot figure out the reason, and this is my first question.
Meanwhile, when I fed the ENTREZID to enrichKEGG, it show me two unreasonable results:
```
kegg_enrich <- enrichKEGG(gene = new_ids$ENTREZID,
                          organism = 'hsa',
                          keyType = 'ncbi-geneid',
                          pvalueCutoff = 0.05,
                          #pAdjustMethod = 'BH',
                          #qvalueCutoff = 0.2,
                          use_internal_data = FALSE)
```
`head(kegg_enrich)`
```
              ID                           Description GeneRatio  BgRatio       pvalue   p.adjust     qvalue
hsa04380 hsa04380            Osteoclast differentiation    14/281 128/7299 0.0003817040 0.04767338 0.04508266
hsa04070 hsa04070 Phosphatidylinositol signaling system    12/281  99/7299 0.0003875885 0.04767338 0.04508266
```
I noted that only 281 genes are remained(there are 700+ genes in my list). In case that there is something wrong wtihin my gene list, I also tried my list with DAVID. It gave me reasonable results. So this is my second question, why enrichKEGG cannot recognize my geneids? 
Thanks!

Yang

**Comment by GuangchuangYu** [comment]
The parameter is `keyType` and you just misspell it.

For KEGG issue, `clusterProfiler` is absolutely out-perform DAVID.

![screenshot 2017-11-07 20 32 00](https://user-images.githubusercontent.com/626539/32494002-e6521190-c3fa-11e7-9baf-1bc6d31daaf6.png)

I upload your gene list to `DAVID`, and the result indicate that `DAVID` only have 197 genes annotated.

`clusterProfiler` have >40% more genes annotated by KEGG compare to `DAVID`:

```
> (281-197)/197
[1] 0.4263959
```

`clusterProfiler` provides many useful utilities, making it possible to check manually.

```r
> bitr_kegg(geneID = new_ids$ENTREZID, fromType='ncbi-geneid', toType='Path', organism='hsa') -> xx
Warning message:
In bitr_kegg(geneID = new_ids$ENTREZID, fromType = "ncbi-geneid",  :
  62.98% of input gene IDs are fail to map...
> head(xx)
  ncbi-geneid     Path
1       10023 hsa04310
2       10023 hsa05224
3       10023 hsa05225
4       10057 hsa01523
5       10057 hsa02010
6       10114 hsa04218
> new_ids$ENTREZ[!new_ids$ENTREZID %in% xx[, "ncbi-geneid"]] %>% head
[1] "100506775" "143458"    "57649"     "54899"     "220323"    "8728"
```
 
You can verify it on KEGG website, the gene annotation in KEGG website can be access via the link `http://www.genome.jp/dbget-bin/www_bget?hsa:ENTREZID`. 

For example,  the gene, `10023`, has KEGG Pathway annotation and you can verify it via <http://www.genome.jp/dbget-bin/www_bget?hsa:10023>. 

While the gene, `100506775`, that doesn't have Pathway annotation can also be checked via <http:www.genome.jp/dbget-bin/www_bget?hsa:100506775>.


KEGG mainly focus on metabolic pathways, and it is true that many genes do not have KEGG annotation. You may want to try `ReactomePA` for using Reactome pathway database.

**Comment by GuangchuangYu** [comment]
Vignette corrected for first question, <https://github.com/GuangchuangYu/clusterProfiler/commit/6352683788121b8ff1a3dde3312fbe096e3f9f52#diff-504b4bdb4708187725ced3b8ab494775>.

**Comment by snoopy-448** [comment]
Thank you for so fast reply! I know what's wrong with my KEGG analysis. I choose all database on the DAVID, so there are many genes being mapped.
For my first question, if I use keyType, it will tell me: 
`Error in enrichGO(gene = input_ids, OrgDb = org.Hs.eg.db, keyType = "ENSEMBL",  : 
  unused argument (keyType = "ENSEMBL")`
It seems that the correct argument for my clusterprofiler version is keytype.

**Comment by GuangchuangYu** [comment]
you need to upgrade to latest release, <https://github.com/GuangchuangYu/clusterProfiler/blob/master/R/enrichGO.R#L37>.

I change the `keytype` to `keyType` for consistency among different functions.

**Comment by xie186** [comment]
> The parameter is `keyType` and you just misspell it.
> 
> For KEGG issue, `clusterProfiler` is absolutely out-perform DAVID.
> 
> ![screenshot 2017-11-07 20 32 00](https://user-images.githubusercontent.com/626539/32494002-e6521190-c3fa-11e7-9baf-1bc6d31daaf6.png)
> 
> I upload your gene list to `DAVID`, and the result indicate that `DAVID` only have 197 genes annotated.
> 
> `clusterProfiler` have >40% more genes annotated by KEGG compare to `DAVID`:
> 
> ```
> > (281-197)/197
> [1] 0.4263959
> ```
> 
> `clusterProfiler` provides many useful utilities, making it possible to check manually.
> 
> ```r
> > bitr_kegg(geneID = new_ids$ENTREZID, fromType='ncbi-geneid', toType='Path', organism='hsa') -> xx
> Warning message:
> In bitr_kegg(geneID = new_ids$ENTREZID, fromType = "ncbi-geneid",  :
>   62.98% of input gene IDs are fail to map...
> > head(xx)
>   ncbi-geneid     Path
> 1       10023 hsa04310
> 2       10023 hsa05224
> 3       10023 hsa05225
> 4       10057 hsa01523
> 5       10057 hsa02010
> 6       10114 hsa04218
> > new_ids$ENTREZ[!new_ids$ENTREZID %in% xx[, "ncbi-geneid"]] %>% head
> [1] "100506775" "143458"    "57649"     "54899"     "220323"    "8728"
> ```
> 
> You can verify it on KEGG website, the gene annotation in KEGG website can be access via the link `http://www.genome.jp/dbget-bin/www_bget?hsa:ENTREZID`.
> 
> For example, the gene, `10023`, has KEGG Pathway annotation and you can verify it via http://www.genome.jp/dbget-bin/www_bget?hsa:10023.
> 
> While the gene, `100506775`, that doesn't have Pathway annotation can also be checked via http:www.genome.jp/dbget-bin/www_bget?hsa:100506775.
> 
> KEGG mainly focus on metabolic pathways, and it is true that many genes do not have KEGG annotation. You may want to try `ReactomePA` for using Reactome pathway database.

Hi @GuangchuangYu,

Could you please explain me what the difference between `ENTREZID` and `ncbi-geneid`? Thanks.

Best,
Shaojun Xie

**Comment by GuangchuangYu** [comment]
`enrichDAVID` is more restricted than `DAVID` as you can find `pAjustMethod` and `qvalueCutoff` in the parameter list. If you want to compare the results, you need to make sure whether the settings are identical.

The `ncbi-geneid` is the key ID used by KEGG database and it can be any type of IDs. I don't know what it is for a specific species. It just happened to be ENTREZ for human.

**Comment by jajcobyang** [comment]
Hi Guangchuang,

Thank you for your excellent book https://yulab-smu.github.io/clusterProfiler-book/chapter6.html.
I tried the chapter 6, everything went smoothly, but I got stuck in the following 6.4 part
mkk2 <- gseMKEGG(geneList = geneList,
                 species = 'hsa')
when I ran this, an error occurred as follows:
Error in gseMKEGG(geneList = geneList, species = "hsa") : 
  unused argument (species = "hsa")

I tried remove the species = 'hsa', then following notice poped out,
preparing geneSet collections...
GSEA analysis...
no term enriched under specific pvalueCutoff...

I looked up the documentation with ?gseMKEGG and found that there was no argument named 'species'

really confused.

**Comment by GuangchuangYu** [comment]
@jajcobyang  thanks, the typo was corrected.

**Comment by yzJiang9** [comment]
Hi Guangchuang, I am wondering whether I can use ensembl id for `enrichKEGG`? Error in KEGG_convert("kegg", keyType, species) : 
  ENSEMBL is not supported for hsa ...
