### ISSUE TITLE
Error with ecolik12 enrichGO

### ISSUE THREAD

**Issue by taiyebzahir** [GuangchuangYu/clusterProfiler#117]
Hi 
I am new to clusterprofiler. I could use the groupGO easily on the set of genes but enrichGO throws an error saying "Error in enrichGO(gene = cephalexinlist, organism = "ecolik12", ont = "BP",  : 
  unused argument (organism = "ecolik12")".  The script is below. What am I doing wrong here? Please any help will be appreciated. Many thanks in advance. 

library(clusterProfiler)

list<-c("947767",	"947672",	"947507",	"945554",	"946343",	"945972",	"945947",	"946526",	"944968",	"948848",	"948661",	"945059",	"948650",	"946185",	"947449",	"948698",	"945278",	"947095",	"948665",	"945957",	"947019",	"946107",	"946243",	"944797",	"946677",	"948666",	"946053",	"948150",	"947189",	"948566")
enrichedgo <- enrichGO(list, organism="ecolik12", ont = "BP", pvalueCutoff = 0.05, readable = TRUE)

**Comment by GuangchuangYu** [comment]
you just ignore my [message](https://github.com/GuangchuangYu/clusterProfiler/issues/new).

**Comment by GuangchuangYu** [comment]
answer [here](https://support.bioconductor.org/p/103398/#103399).
