### ISSUE TITLE
GO term not found error, Yeast data, gseGO test

### ISSUE THREAD

**Issue by Deanho** [GuangchuangYu/clusterProfiler#12]
Hi,

I am trying to use gseGO enrichment test on my data, which contains yeast ORF identifiers (Table$IDs). If I try (for example):
ego2 <- gseGO(geneList = Table$IDs, organism = "yeast",  ont = "MF",
              nPerm = 100, minGSSize = 120, pvalueCutoff = 0.01, verbose = FALSE)

I get the following error:

Error in .checkKeys(value, Lkeys(x), x@ifnotfound) : 
  value for "GO:0010834" not found

This is also true if I test for GO CC or GO BP too. This GO term seems to be deprecated now. How I can I get around this error?

Best Regards,

Dean

**Comment by GuangchuangYu** [comment]
Hi Dean,

Can you give me some sample IDs that can replicate this issue?

**Comment by Deanho** [comment]
Hi Guangchuang,

Table$IDs are in the attached .txt file.

Regards,

Dean

**Comment by GuangchuangYu** [comment]
thanks for your report.

Yes, it's due to deprecated GO term.

This issue had been removed in clusterProfiler version >=2.2.3

BTW: I also detect wrong usage in your command:
```r
ego2 <- gseGO(geneList = Table$IDs, organism = "yeast", ont = "MF",
nPerm = 100, minGSSize = 120, pvalueCutoff = 0.01, verbose = FALSE)
```

geneList should not be a vector of gene IDs, but a vector of order numerical number (eg fold change, pvalues) and named by corresponding gene IDs.

**Comment by Deanho** [comment]
OK. Thanks! That's great. Thanks for correcting the code too.....!

**Comment by Deanho** [comment]
Hi,

Clusterprofiler would not update unless I use the devel=TRUE in biocLite. I have done this but still get the same error when I try the ego2 test (with the correct geneList!).
I also see the following when loading clusterProfiler:
> library(clusterProfiler)
Loading required package: DBI

Warning message:
replacing previous import by ‘graph::.__C__dist’ when loading ‘topGO’ 

Any ideas? Sorry to bother you about this!

Regards,

Dean

**Comment by GuangchuangYu** [comment]
You should wait 2-3 days for Bioconductor to update tallbar.

Don't mixed release and devel versions of Bioconductor packages. That may introduce a lot of issues.

**Comment by Deanho** [comment]
OK. Thanks Guangchuang.
