### ISSUE TITLE
DOSE.rdb corrupted

### ISSUE THREAD

**Issue by StephaneKazmierczak** [GuangchuangYu/clusterProfiler#120]
Hello using R 3.3.3 and devtools::install_github("guangchuangyu/clusterProfiler")
I am getting R/x86_64-pc-linux-gnu-library/3.3/DOSE/R/DOSE.rdb' is corrupt

**Comment by GuangchuangYu** [comment]
close R, then reopen it to install.

The issue here is that DOSE was loaded before you try to install it.

**Comment by StephaneKazmierczak** [comment]
Thank you so much it works right away
