### ISSUE TITLE
what is the difference between 'p.adjust' and 'qvalue' 

### ISSUE THREAD

**Issue by lmolla** [GuangchuangYu/clusterProfiler#124]
Another question here ( sorry if too basic)

what is the difference between 'p.adjust' and 'qvalue' 
in the overrepresentation test using the hypergeometric model
example in the enrichPathway function.

**Comment by GuangchuangYu** [comment]
pls refer to their manuals.

```r
?p.adjust 
?qvalue::qvalue
```
