### ISSUE TITLE
Customize plot colors

### ISSUE THREAD

**Issue by eshelden** [GuangchuangYu/clusterProfiler#128]
Dear Guangchuang,

Thank you for developing these excellent resources. I was wondering if there is a simple way to change the color palette used to make the dotplots? In your code I see something referred to as enrichplot:::sig_palette, but no way to change it.

Thank you again!

Eric Shelden

**Comment by GuangchuangYu** [comment]
see here, <https://github.com/GuangchuangYu/enrichplot/issues/4>, and you are welcome to propose new color scheme.

**Comment by eshelden** [comment]
Excellent! Thank you!
