### ISSUE TITLE
browsekegg does not highlight any genes

### ISSUE THREAD

**Issue by eshelden** [GuangchuangYu/clusterProfiler#129]
Sorry for asking what I'm sure is a trivial question, but I can't seem to figure out why browsekegg is not highlighting any genes in red in the example below, although it works when I follow the clusterprofiler vignette. The graph shows the output of dotplot, so I know some gene clusters are found.  I also see that in the vignette, the call to kegg.org looks like this:

http://www.kegg.jp/kegg-bin/show_pathway?hsa04110/8318/991/9133/890/983/4085/7272/1111/891/4174/9232

However, the code below produces this call:
http://www.kegg.jp/kegg-bin/show_pathway?hsa04110/NA

Thank you for any advice!

Eric

x <- c("GPX3",  "GLRX",   "LBP",   "CRYAB", "DEFB1", "HCLS1",   "SOD2",   "HSPA2",
       "ORM1",  "IGFBP1", "PTHLH", "GPC3",  "IGFBP3","TOB1",    "MITF",   "NDRG1",
       "NR1H4", "FGFR3",  "PVR",   "IL6",   "PTPRM", "ERBB2",   "NID2",   "LAMB1",
       "COMP",  "PLS3",   "MCAM",  "SPP1",  "LAMC1", "COL4A2",  "COL4A1", "MYOC",
       "ANXA4", "TFPI2",  "CST6",  "SLPI",  "TIMP2", "CPM",     "GGT1",   "NNMT",
       "MAL",   "EEF1A2", "HGD",   "TCN2",  "CDA",   "PCCA",    "CRYM",   "PDXK",
       "STC1",  "WARS",  "HMOX1", "FXYD2", "RBP4",   "SLC6A12", "KDELR3", "ITM2B",
       "ROCK","PTEN","FAK","PKC")
eg = bitr(x, fromType="SYMBOL", toType="UNIPROT", OrgDb="org.Hs.eg.db")
kk <- enrichKEGG(gene         = eg$UNIPROT,
                 keyType = "uniprot",
                 organism     = 'hsa',
                 pvalueCutoff = 0.05)
head(kk)
dotplot(kk, showCategory=20)
browseKEGG(kk, 'hsa04510')

![rplot](https://user-images.githubusercontent.com/15791391/36921332-db2452ce-1e18-11e8-9bd6-0ce1f4078c80.jpeg)

![hsa04510_0 82140249](https://user-images.githubusercontent.com/15791391/36921365-f8f38964-1e18-11e8-9e24-d8d4cd456312.png)

**Comment by eshelden** [comment]
Ah. So, if I convert the symbols to ENTREZID, then it works. Here's code that works, if anyone finds it useful:

x <- c("GPX3",  "GLRX",   "LBP",   "CRYAB", "DEFB1", "HCLS1",   "SOD2",   "HSPA2",
       "ORM1",  "IGFBP1", "PTHLH", "GPC3",  "IGFBP3","TOB1",    "MITF",   "NDRG1",
       "NR1H4", "FGFR3",  "PVR",   "IL6",   "PTPRM", "ERBB2",   "NID2",   "LAMB1",
       "COMP",  "PLS3",   "MCAM",  "SPP1",  "LAMC1", "COL4A2",  "COL4A1", "MYOC",
       "ANXA4", "TFPI2",  "CST6",  "SLPI",  "TIMP2", "CPM",     "GGT1",   "NNMT",
       "MAL",   "EEF1A2", "HGD",   "TCN2",  "CDA",   "PCCA",    "CRYM",   "PDXK",
       "STC1",  "WARS",  "HMOX1", "FXYD2", "RBP4",   "SLC6A12", "KDELR3", "ITM2B",
       "ROCK","PTEN","FAK","PKC")
eg = bitr(x, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
kk <- enrichKEGG(gene = eg$ENTREZID,
                 organism = 'hsa',
                 pvalueCutoff = 0.05)
#head(kk)
#dotplot(kk, showCategory=20)
browseKEGG(kk, 'hsa04151')

**Comment by GuangchuangYu** [comment]
currently, `browserKEGG` only works with default kegg ID (ENTREZID for human).

**Comment by eshelden** [comment]
Thank you for your help!
Cheers,
Eric
