### ISSUE TITLE
Input format for GSE analyses

### ISSUE THREAD

**Issue by PFRoux** [GuangchuangYu/clusterProfiler#13]
Dear Guangchuang,

I carefully read the vignette coming with clusterProfiler, but didn't find how to format the geneList input object for gseKEGG and gseGO function.

Any help would be greatly appreciated.

Thanks a lot !

Pierre-François

**Comment by GuangchuangYu** [comment]
```r
> str(geneList)
 Named num [1:12495] 4.57 4.51 4.42 4.14 3.88 ...
 - attr(*, "names")= chr [1:12495] "4312" "8318" "10874" "55143" ...
> head(geneList)
    4312     8318    10874    55143    55388      991
4.572613 4.514594 4.418218 4.144075 3.876258 3.677857
> head(names(geneList))
[1] "4312"  "8318"  "10874" "55143" "55388" "991"
```
The geneList input is sorted numerical number (eg foldchange) from largest to smallest and the numbers were named by their corresponding gene ID.

**Comment by PFRoux** [comment]
Thanks a lot for your really quick answer !

Regards,

Pierre-François
