### ISSUE TITLE
Using clusterprofiler on KOs that have already been annotated

### ISSUE THREAD

**Issue by lwebercoralgirl** [GuangchuangYu/clusterProfiler#130]
Hello,

I have a data matrix of significantly different KO counts generated using the FMAP pipeline for each of my samples and I would like to cluster these KOs into pathways for each sample and then plot them using the dotplot function in clusterprofiler by sample.

Is there a way I can accomplish this?

Thanks!

**Comment by GuangchuangYu** [comment]
just use `organism="ko"` in `enrichKEGG` or `gseKEGG`.
