### ISSUE TITLE
What about user-defined database?

### ISSUE THREAD

**Issue by hzafeng** [GuangchuangYu/clusterProfiler#131]
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [x] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [x] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

**Comment by hzafeng** [comment]
If i want to run Enrichment Analysis use my local database such as db of COG, Can i i use ClusterProfile ,if yes ,how can i use it?

**Comment by GuangchuangYu** [comment]
yes, and it was documented on <http://guangchuangyu.github.io/2015/05/use-clusterprofiler-as-an-universal-enrichment-analysis-tool/>.
