### ISSUE TITLE
a mistake about package or namespace load failed for ‘clusterProfiler’:

### ISSUE THREAD

**Issue by zyb1984** [GuangchuangYu/clusterProfiler#132]
MISTAKE: package or namespace load failed for ‘clusterProfiler’:'namespace:DOSE'没有出口‘dotplot’这个对象

**Comment by zyb1984** [comment]
> library("DOSE")

DOSE v3.5.1  For help: https://guangchuangyu.github.io/DOSE

If you use DOSE in published research, please cite:
Guangchuang Yu, Li-Gen Wang, Guang-Rong Yan, Qing-Yu He. DOSE: an R/Bioconductor package for Disease Ontology Semantic and Enrichment analysis. Bioinformatics 2015, 31(4):608-609

> library("clusterProfiler")
错误: package or namespace load failed for ‘clusterProfiler’:
 'namespace:DOSE'没有出口‘dotplot’这个对象
> library("ReactomePA")
错误: package or namespace load failed for ‘ReactomePA’:
 'namespace:DOSE'没有出口‘netplot’这个对象

**Comment by GuangchuangYu** [comment]
YOU already know the reason is due to the upgrade of `DOSE`, and as you know the reason, you should know how to fix it too.

**Comment by GuangchuangYu** [comment]
an explanation (in Chinese) can be found [HERE](https://mp.weixin.qq.com/s/CyiIJNwAQkyHQ5OVU9oa7w).

**Comment by Cristinex** [comment]
Hi. I tried to follow the instruction to install github version clusterProfiler with devtools. However, it still shows error for RcppEigen.
ERROR: compilation failed for package ‘RcppEigen’.
Could you please help me with this problem?@GuangchuangYu
