### ISSUE TITLE
Error: package or namespace load failed for ‘clusterProfiler’

### ISSUE THREAD

**Issue by Huffyphenix** [GuangchuangYu/clusterProfiler#133]
### An error about DOSE occured when I installed clusterProfiler or library it.

DOSE package was installed from bioconductor source code by downloading the DOSE_3.5.1.tar.gz package, and install it on Rstutio with install.packages()

The same as DOSE, but I got an error when I try to install clusterProfiler, error says:
Error : object 'dotplot' is not exported by 'namespace:DOSE'
ERROR: lazy loading failed for package 'clusterProfiler'

So I change my way to install clusterProfiler by biocLite, no error occurded during installation, but an error the same as above occured when I try to library it:
Error: package or namespace load failed for ‘clusterProfiler’:
object 'dotplot' is not exported by 'namespace:DOSE'

The version of R and DOSE  all meet the requirement:

>packageVersion("DOSE")
[1] ‘3.5.1’

>R.version
_
platform x86_64-w64-mingw32
arch x86_64
os mingw32
system x86_64, mingw32
status
major 3
minor 4.3
year 2017
month 11
day 30
svn rev 73796
language R
version.string R version 3.4.3 (2017-11-30)
nickname Kite-Eating Tree

What‘’s the problem with my installation？How can I solve it? 
Thanks.

**Comment by GuangchuangYu** [comment]
see also <https://github.com/GuangchuangYu/clusterProfiler/issues/132>.

**Comment by Huffyphenix** [comment]
Thanks ☀️
