### ISSUE TITLE
Getting error not exported by 'namespace:DOSE

### ISSUE THREAD

**Issue by bikash1992** [GuangchuangYu/clusterProfiler#134]
I had also installed latest package, and still getting this error.

>library(ReactomePA)

Error: package or namespace load failed for ‘ReactomePA’:

object ‘netplot’ is not exported by 'namespace:DOSE'

>yy = enrichPathway(gene, pvalueCutoff=0.05)

Error in enrichPathway(gene, pvalueCutoff = 0.05) :

could not find function "enrichPathway"

>library(clusterProfiler)

Error: package or namespace load failed for ‘clusterProfiler’:

object ‘dotplot’ is not exported by 'namespace:DOSE'

**Comment by GuangchuangYu** [comment]
duplicated. <https://github.com/GuangchuangYu/clusterProfiler/issues/132>
