### ISSUE TITLE
ClusterProfiler Ontology Bar plotting

### ISSUE THREAD

**Issue by bikash1992** [GuangchuangYu/clusterProfiler#135]
I am doing gene ontology enrichment with cluterprofiler package, and I got the result but when I plotting barplot (10000 descriptions) it's difficult to read or identify the name in the plot, is there any method to remove those descriptions which don't have any gene name.
Command Line

>ggo <- groupGO(gene = UPT2,

OrgDb = org.Hs.eg.db,

ont = "MF",

level = 3,

readable = TRUE)

>barplot(ggo, drop=TRUE, font.size = 10,showCategory=10000, title="Up Treated2 Biological Process"

**Comment by GuangchuangYu** [comment]
duplicated. <https://www.biostars.org/p/305624/>.
