### ISSUE TITLE
how to directly convert the result geneID into symbol in enrichKEGG/enrichGO result file? 

### ISSUE THREAD

**Issue by pangxueyu** [GuangchuangYu/clusterProfiler#143]
I am new to bioinformatic and appreciate to clusterProfiler packages. But recently, I just want to convert my geneID column into gene symbol directly. How should I try? 
![image](https://user-images.githubusercontent.com/37611716/40290594-7e2aa3b2-5cf1-11e8-8294-6c0f0f471ffb.png)

**Comment by pangxueyu** [comment]
we have both human and mouse result dividually.

**Comment by dongzhuoer** [comment]
For human genes, you may try my package hgnc

```r
devtools::install_github('dongzhuoer/hgnc');

library(magrittr)
> c(23141, 5925) %>% hgnc::as_symbol_from_entrez()
[1] "ANKLE2" "RB1"  
```

**Comment by dongzhuoer** [comment]
By the way, what you report is more a question than a issue, so you are not supposed to ask here.

**Comment by GuangchuangYu** [comment]
You can use `setReadable` function and there is example presented on [vignette](https://bioconductor.org/packages/release/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html).
