### ISSUE TITLE
padjustMethod explanations

### ISSUE THREAD

**Issue by Gkandoi** [GuangchuangYu/clusterProfiler#147]
Hi

I've read the documentations and the papers for reactomePA, clusterProfiler and DOSE but can't find what the padjustMethods, "BH", "BY" stand for?

I'm assuming "BH" refers to the Benjamini-Hochberg method, but I would like to be sure.

Thanks
Gaurav

**Comment by JonathanWenger** [comment]
"BY" stands for Benjamini & Yekutieli. clusterProfiler uses the same adjustment methods as the R function stats::p.adjust. See the documentation for explanations of "BH", "BY", etc.: https://www.rdocumentation.org/packages/stats/versions/3.5.0/topics/p.adjust

**Comment by Gkandoi** [comment]
Thanks
