### ISSUE TITLE
Issues with enrichKEGG heatplot, and gseGO & gseKEGG tests 

### ISSUE THREAD

**Issue by fib4206** [GuangchuangYu/clusterProfiler#152]
Hello all, I recently began coding in R and using clusterProfileras per my thesis. I was playing around with the geneList sample provided via DOSE, and was able to successfully run both an enrichGO and enrichKEGG test on a few of the genes from geneList-- I even managed to construct a heatmap. 

However, I noticed something peculiar about the enrichKEGG heatmap. Where the enrichGO heatmap was able to display the gene symbols on the heat plot axis, the enrichKEGG heatmap instead displayed the gene ID numbers. I've provided the code I used, and the enrichKEGG heatplot for reference. You'll see a list of gene ID's along the Y-axis:

                                  `data(geneList, package="DOSE")
                                   gene <- names(geneList)
                                   gene.df <- bitr(gene, fromType = "ENTREZID",
                                                            toType = c("ENSEMBL", "SYMBOL"),
                                                            OrgDb = org.Hs.eg.
                                   de <- names(geneList)[1:60]
                                   kk <- enrichKEGG(de, organism     = 'hsa',  pvalueCutoff = 0.05)
                                   final_productKEGG_Overrep <- heatplot(kk, foldChange = geneList, showCategory 
                                                                                                      = 20000)+ ggplot2::coord_flip()
                                   
                                   final_productKEGG_Overrep`

![enrichkegg_heatplot_of_60_dose_genelist_genes](https://user-images.githubusercontent.com/40434128/41670639-d5c28e02-7482-11e8-8a27-b373610a36cb.jpeg)

### **My first question is simple:**

_How do you replace the gene ID's with the gene symbol on the axis of an enrichKEGG heatmap?_

I was also trying to run a gseGO and gseKEGG on a small number of genes from the DOSE geneList (around 20-30) and I was getting the following error message from a gseGO:

                      `  preparing geneSet collections...
                        GSEA analysis...
                        Error in FUN(X[[i]], ...) : 
                          GSEA statistic is not defined when all genes are selected` 

And I get this error message from a gseKEGG, even after setting the pValueCutoff to different values, and getting rid of the argument entirely:

                         `preparing geneSet collections...
                         GSEA analysis...
                         no term enriched under specific pvalueCutoff...`

However, this error message does not appear when I run the full DOSE geneList through a gseGO and gseKEGG.

###  **My second question is this:**

_Are the gseGO and gseKEGG both dependent on sample size, such that geneLists with small sample sizes cannot be performed using these tests? Why else would I get getting these messages?_

**Comment by GuangchuangYu** [comment]
duplicated, <https://github.com/GuangchuangYu/enrichplot/issues/10>.
