### ISSUE TITLE
Example in compareCluster does not work

### ISSUE THREAD

**Issue by lukeholman** [GuangchuangYu/clusterProfiler#156]
Pasting the example lines of code one at a time in a fresh session, I get as far as the line that says `plot(xx, type="dot", caption="KEGG Enrichment Comparison")`. It returns the error 
```
Error in as.double(y) : 
  cannot coerce type 'S4' to vector of type 'double'
```

**Comment by GuangchuangYu** [comment]
pls use `dotplot`.

**Comment by zunwang95** [comment]
> pls use `dotplot`.
Hi,

I'm facing the same trouble and doPlot doesn't work

ERR code:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘doPlot’ for signature ‘"compareClusterResult"’
