### ISSUE TITLE
clusterprofiler seems to not work for groupGO for organism="ecsakai"!!

### ISSUE THREAD

**Issue by nandan75** [GuangchuangYu/clusterProfiler#16]
Hi,

I have been using clusterprofiler with good effect for a while now. Thanks.

I have used the similar commands for a set of genes in human and then a different set of genes in "ecsakai" for "Functional Profile of a gene sets"..
With "human" everything works fine.
When I run the command below, I get no output..

Command
ggo <- groupGO(gene=AllGenes_EntrezIds, organism="ecsakai", ont ="BP", level=4, readable = FALSE)

In analysis for "ecsakai", I have confirmed that the variable "AllGenes_EntrezIds" contains the EntrezIds in the required format (same format as in humans).

Output
> head(summary(ggo))
                   ID                                           Description Count GeneRatio geneID
GO:0000747 GO:0000747                      conjugation with cellular fusion     0    0/5195       
GO:0000909 GO:0000909 sporocarp development involved in sexual reproduction     0    0/5195       
GO:0007276 GO:0007276                                     gamete generation     0    0/5195       
GO:0007618 GO:0007618                                                mating     0    0/5195       
GO:0009566 GO:0009566                                         fertilization     0    0/5195       
GO:0034293 GO:0034293                                    sexual sporulation     0    0/5195  

Appreciate your assistance,

Nandan

**Comment by GuangchuangYu** [comment]
this should be an issue of the input gene IDs. Can you just paste a few of them here?

**Comment by nandan75** [comment]
Thanks for your reply.

These are the top few GeneIds , which i am submitting to the groupGO step
"913387" "913388" "913390" "913393" "913394" "913395" 

cheers,

Nandan

**Comment by GuangchuangYu** [comment]
No GO annotation can be found with your input genes:
```r
> require(org.EcSakai.eg.db)
> g
[1] "913387" "913388" "913390" "913393" "913394" "913395"
> select(org.EcSakai.eg.db, keys=g, columns=c("GO", "ONTOLOGY"), keytype="ENTREZID")
  ENTREZID   GO EVIDENCE ONTOLOGY
1   913387 <NA>     <NA>     <NA>
2   913388 <NA>     <NA>     <NA>
3   913390 <NA>     <NA>     <NA>
4   913393 <NA>     <NA>     <NA>
5   913394 <NA>     <NA>     <NA>
6   913395 <NA>     <NA>     <NA>
>
```

**Comment by nandan75** [comment]
Thanks for efforts..

I checked your command

"select(org.EcSakai.eg.db, keys=g, columns=c("GO", "ONTOLOGY"),
keytype="ENTREZID")"

WITH  the variable 'g' containing *ALL the 5000+ geneIds in the
"EcSakai" genome *. It still gives *all <NA>* output!!!


2484   917459 <NA>     <NA>     <NA>
2485   913037 <NA>     <NA>     <NA>
2486   916669 <NA>     <NA>     <NA>
2487   917168 <NA>     <NA>     <NA>
2488   917462 <NA>     <NA>     <NA>
2489   912535 <NA>     <NA>     <NA>
2490   913041 <NA>     <NA>     <NA>
2491   913377 <NA>     <NA>     <NA>
2492   916671 <NA>     <NA>     <NA>
2493   917172 <NA>     <NA>     <NA>
2494   917461 <NA>     <NA>     <NA>
2495   913044 <NA>     <NA>     <NA>


But When I run the above command, with human ENTREZIDs in the variable 'g'

"select(*org.Hs.eg.db*, keys=g, columns=c("GO", "ONTOLOGY"),
keytype="ENTREZID")".

I get a proper answer..

2476       9099 GO:0050821      IMP       BP
2477       9099 GO:0061136      IBA       BP
2478      79605 GO:0016021      IEA       CC
2479      57568 GO:0005096      IEA       MF
2480      57568 GO:0005515      IPI       MF
2481      57568 GO:0043547      IEA       BP
2482      23321 GO:0004842      ISS       MF
2483      23321 GO:0005515      IPI       MF
2484      23321 GO:0005737      IDA       CC
2485      23321 GO:0008270      NAS       MF
2486      23321 GO:0016567      IEA       BP
2487      23321 GO:0016874      IEA       MF
2488      23321 GO:0043523      ISS       BP
2489       6574 GO:0004871      IMP       MF
2490       6574 GO:0004872      TAS       MF
2491       6574 GO:0005315      IEA       MF
2492       6574 GO:0005316      IEA       MF

*Is there a possibility that the back-end Gene-Ontology data for the
organism "EcSakai" is not being accessed properly for some reason?*


Appreciate your efforts in assisting me,

Cheers,

Nandan

**Comment by GuangchuangYu** [comment]
If you check the specific GO bimap, it seems the bimap doesn't contain any keys.
```r
> keys(org.EcSakai.egGO2ALLEGS)
character(0)
> keys(org.EcSakai.egGO2EG)
character(0)
>
```

I posted this issue in [https://support.bioconductor.org/p/70277/](https://support.bioconductor.org/p/70277/).

**Comment by nandan75** [comment]
Thanks for that..

In the meantime do you think I should use the buildGOMap() method to create
my own maps? as shown in the link below?

http://rgm.ogalab.net/RGM-files/R_BC/download/clusterProfiler/inst/doc/clusterProfiler_for_unsupported_organisms.pdf


As I understand, I need to blast2Go my sequences, retrieve Gene
ontologies..and provide those to the above function?

cheers,

Nandan

**Comment by GuangchuangYu** [comment]
Yes, you can use `buildGOMap` to generate your own annotation file that suitable for `enrichGO` function.

**Comment by nandan75** [comment]
Thanks very much

**Comment by GuangchuangYu** [comment]
A reply in [https://support.bioconductor.org/p/70277/](https://support.bioconductor.org/p/70277/):
```
The GO annotations are based on the gene2go file from NCBI, and if you look at the species for which there are mappings between Entrez Gene ID and GO ID, there is only one E. coli strain, the K12, which has a taxon ID of 511145
```
