### ISSUE TITLE
dotplot of compareCluster error unless 'showCategory=TRUE'

### ISSUE THREAD

**Issue by monalisawi** [GuangchuangYu/clusterProfiler#161]
I used the compareCluster function to compute KEGG profiles of my gene clusters following the vignette and using func="enricher" as [stated previously](https://support.bioconductor.org/p/84309/). When I passed my compareClusterResult object to the dotplot function, I get an error: 

'library(clusterProfiler)'

'object@compareClusterResult' #snippet of output from compareCluster function. Everything seems fine
![image](https://user-images.githubusercontent.com/43186421/45386791-1dee2380-b5c9-11e8-8126-e2a13dbe41e0.png)
 

`dotplot(object, x=~Cluster)`
> Error in `levels<-`(`*tmp*`, value = as.character(levels)) : factor level [7] is duplicated 

When I add in the argument `showCategory=TRUE` I get the plot I was expecting, though with fewer categories than I expected:

`dotplot(object, x=~Cluster, showCategory=TRUE)`
![image](https://user-images.githubusercontent.com/43186421/45386150-758b8f80-b5c7-11e8-958c-ff09980928af.png)

I would like to have a dotplot with more categories, but I can only seem to get a plot when 'showCategory=TRUE' and not when I enter a number, no matter how large or small the number is. _**Why do I get an error using the dotplot function unless 'showCategory=TRUE'? And how can I successfully create a dotplot with more categories?**_

'> sessionInfo()'
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.30.0  clusterProfiler_3.8.1

Thank you in advance,
Lisa

**Comment by GuangchuangYu** [comment]
any reproducible example?

**Comment by monalisawi** [comment]
Please see below. And I sort of figured it out: my organism is not a model one, so I was using term2gene and term2name files I created myself to go from my genes --> K orthologies --> pathway descriptions. Multiple K orthologies can have the exact same pathway description and that is what led to problems with my dotplot.

Maybe the example will help explain what I mean:

`library("DOSE")
library("clusterProfiler")
library("tidyr")

data(geneList)

mydf <- data.frame(Entrez=names(geneList), FC=geneList)
mydf <- mydf[abs(mydf$FC) > 1,] #cuts down df size

#create different groups to cluster by
mydf$FCgroup <- "medium"
mydf <- within(mydf, FCgroup[FC< 0] <- "low")
mydf <- within(mydf, FCgroup[FC< -2] <- "lowest")
mydf <- within(mydf, FCgroup[FC> 2] <- "high")
mydf <- within(mydf, FCgroup[FC> 3] <- "highest")

compared<- compareCluster(Entrez~FCgroup, data=mydf, fun="enrichKEGG") #dotplot of compared works as expected

#Now, I change one of the ID's associated with "Cell Cycle" description in the compareClusterResult object so there are now two different ID's sharing the same Description:
compared@compareClusterResult$ID[compared@compareClusterResult$Cluster=="highest" & compared@compareClusterResult$ID=="hsa04110"] <- "hsa00000" #changes ID for sample #9, but doesn't affect Description or Cluster columns

compared@compareClusterResult'
![image](https://user-images.githubusercontent.com/43186421/45446892-f360a100-b682-11e8-8e92-182f91f403f0.png)


'dotplot(compared)

Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [16] is duplicated

dotplot(compared, showCategory=TRUE)`
![image](https://user-images.githubusercontent.com/43186421/45445905-6c122e00-b680-11e8-831a-171161637213.png)

I still don't know why setting 'showCategory = TRUE' makes a graph and I'm not sure how to get around the issue other than by manually changing either the K orthology (aka ID) or the Description in the compareCluster output object before trying to use 'dotplot'. I'd appreciate any suggestions.

Thanks,
Lisa

**Comment by GuangchuangYu** [comment]
if you change the internal data to a wrong format, I can't help.

for the `showCategory = TRUE` issue, it is quite easy to understand as `R` parse `TRUE` to be 1.
