### ISSUE TITLE
TERM2GENE syntax

### ISSUE THREAD

**Issue by Tillsa** [GuangchuangYu/clusterProfiler#166]
Dear Guangchuang Yu,

I want to run your function GSEA with my own TERM2GENE list:

GSEA(geneList, exponent = 1, nPerm = 1000, minGSSize = 10,
maxGSSize = 500, pvalueCutoff = 0.05, pAdjustMethod = "BH", TERM2GENE,
TERM2NAME = NA, verbose = TRUE, seed = FALSE, by = "fgsea")

But I don't know how to handle multiple GO terms that are assigned to a single gene.

Let say my data looks like this:
YP_498609.1     GO:0005737; GO:0005524;
YP_498610.1     GO:0005737;
YP_498612.1     GO:0005737; GO:0005524; GO:0003697;

then how does the TERM2GENE data.frame look like?

one line for each combination of term and gene (multiple lines for a single GO term), like this:

 GO:0005737    YP_498609.1
 GO:0005737    YP_498610.1
 GO:0005737    YP_498612.1
 GO:0005524    YP_498609.1
 GO:0005524    YP_498612.1 
 GO:0003697    YP_498612.1

or would there be multiple gene names assigned to one GO Term in one line, like this:

 GO:0005737    YP_498609.1,YP_498610.1,YP_498612.1
 GO:0005524    YP_498609.1,YP_498612.1
 GO:0003697    YP_498612.1

Best regards

Till

**Comment by GuangchuangYu** [comment]
should be the first one.
