### ISSUE TITLE
Plot S4 type variable in a self-defined function or loaded scripts created by groupGO failed. 

### ISSUE THREAD

**Issue by qifasong** [GuangchuangYu/clusterProfiler#168]
Professor Yu,
I met a problem and tried every way of mine. My R version is  V3.5.1 for Win 7. Clusterprofiler is 3.8.

 I try to plot groupGO produced variable (here go_cc), if I put the plotting in a function or load the scripts  from the R console. The barplot or dotplot fails and no error appears both on the screen and in the file. But the barplot works well if I use a simple variable such as "barplot(50)". The barplot also works well if I paste the following in the R console.

#All variables are OK. I carefully check the structure and picture can be obtained in paste mode..
#If pasted, the picture is obtained. It fails if run from loaded script.
>pdf("go_cc.pdf")
>barplot(go_final,showCategory=40,drop=TRUE,font.size=7,title="groupGO Molecular Function")
>dev.off()
>dev.new()
>barplot(go_final,showCategory=40,drop=TRUE,font.size=7,title="groupGO Molecular Function")" 

##This is a function ("go_cc.pdf") {
>pdf("go_cc.pdf")
>barplot(go_final,showCategory=40,drop=TRUE,font.size=7,title="groupGO Molecular Function")  #Only empty PDF file.
>barplot(c(10,20,30))  #This can be saved in the PDF file.
>dev.off()
>dev.new()
>barplot(go_final,showCategory=40,drop=TRUE,font.size=7,title="groupGO Molecular Function") #Nothing shown.
>barplot(c(10,20,30))  #This can be shown.
>return
>}
>up<-GOs(go_cc)  ##Call this function GOs

Many thanks

**Comment by qifasong** [comment]
##This is a function ("go_cc.pdf") {
GOs<-function(go_final){
pdf("go_cc.pdf")
barplot(go_final,showCategory=40,drop=TRUE,font.size=7,title="groupGO Molecular Function") #Only empty PDF file.
barplot(c(10,20,30)) #This can be saved in the PDF file.
dev.off()
dev.new()
barplot(go_final,showCategory=40,drop=TRUE,font.size=7,title="groupGO Molecular Function") #Nothing shown.
barplot(c(10,20,30)) #This can be shown.
return
}
up<-GOs(go_cc) ##Call this function GOs

**Comment by GuangchuangYu** [comment]
see <https://ggplot2.tidyverse.org/reference/print.ggplot.html>
