### ISSUE TITLE
dotplot.compareClusterResult bug

### ISSUE THREAD

**Issue by lixin4306ren** [GuangchuangYu/clusterProfiler#173]
In function `dotplot.compareClusterResult`, it should use `fortify.compareClusterResult` to convert the result to data.frame, not the original `fortify`. Otherwise, it will generate 'NA' for `Cluster` column.

```
dotplot.compareClusterResult <- function(object, x=~Cluster, colorBy="p.adjust", showCategory=5, by="geneRatio",
                                         split=NULL, includeAll=TRUE, font.size=12, title="") {

    df <- fortify(object, showCategory=showCategory, by=by, includeAll=includeAll, split=split)
    plotting.clusterProfile(df, x=x, type="dot", colorBy=colorBy, by=by, title=title, font.size=font.size)
}
```

**Comment by GuangchuangYu** [comment]
fortify is a generic method and it will call `fortify.compareClusterResult` to dispatch by the class of the  `object`.
