### ISSUE TITLE
How to display selected results of clusterprofiler on emapplot? 

### ISSUE THREAD

**Issue by Fang777** [GuangchuangYu/clusterProfiler#175]
Dear Mr Yu,
        The clusterprofiler is wonderful. When I used enrichplot to display the results of GO, it is in the order of top pvalue. But some of the remarkable terms are not of particular concern to me. I want to select some term，which I concerned， to display using emapplot, how can I do it? Thank you very much. I am so glad to see your reply, thank you!
[entrez.txt](https://github.com/GuangchuangYu/clusterProfiler/files/2726200/entrez.txt)
[ego2.txt](https://github.com/GuangchuangYu/clusterProfiler/files/2726201/ego2.txt)
[newgo.txt](https://github.com/GuangchuangYu/clusterProfiler/files/2726202/newgo.txt)

`library(clusterProfiler)
require(clusterProfiler)
library(org.At.tair.db)
x=read.table("entrez.txt",sep = "\t")  #entrez.txt为要做富集的一列entreID
genelist=as.character(x[,1])  
ego <- enrichGO(gene=genelist,OrgDb=org.At.tair.db,ont="BP",
               pAdjustMethod="BH",pvalueCutoff=0.05,
               qvalueCutoff=0.05,minGSSize=1,
               keyType="ENTREZID",readable=FALSE)
ego2 <- simplify(ego)
write.table(ego2,sep="\t","ego2.txt")
x<-read.table("newgo.txt",sep="\t") ##“newgo.txt“” is GO terms of picked out from "ego2.txt".
newgo <- data.frame("x")
emapplot(newgo)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘emapplot’ for signature [‘"data.frame"’]
`

**Comment by GuangchuangYu** [comment]
duplicated, <https://github.com/GuangchuangYu/clusterProfiler/issues/176>.
