### ISSUE TITLE
kegg enrichment using clusterProfiler could not provide gene name

### ISSUE THREAD

**Issue by huangzhiguang2016** [GuangchuangYu/clusterProfiler#178]
Dear professor. When I used clusterProfiler for KEGG annotation, the results only provided gene ID for each pathway, since the function of "enrichKEGG" could not use argument "readable = TRUE" like "enrichGO" function. I have to translate the gene ID to gene name manually. Could you please help me fix this problem? Thank you!

**Comment by GuangchuangYu** [comment]
see <https://yulab-smu.github.io/clusterProfiler-book/chapter13.html#setReadable>
