### ISSUE TITLE
problem about geneList file

### ISSUE THREAD

**Issue by salviadr** [GuangchuangYu/clusterProfiler#18]
hi  YGC,
I have read your clusterProfiler.R  script.The geneList file that you have used in the script contains information as: 
> head(geneList)
    4312     8318    10874    55143    55388      991
4.572613 4.514594 4.418218 4.144075 3.876258 3.677857 
And foldchange have been raised up latser in the script , I want to know how could I get this value of the gene ?

best
salviadr

**Comment by GuangchuangYu** [comment]
see [http://bioconductor.org/packages/devel/bioc/vignettes/DOSE/inst/doc/DOSE.html#enrichdo-function](http://bioconductor.org/packages/devel/bioc/vignettes/DOSE/inst/doc/DOSE.html#enrichdo-function).
