### ISSUE TITLE
Visualization mistakes in emapplot function

### ISSUE THREAD

**Issue by gengboyuhehe** [GuangchuangYu/clusterProfiler#180]
Hi Guangchuang!
I copied the code in document to generate a enrichment map in Rstudio. But there is a difference from the picture in document.
This is the code
library(clusterProfiler)
library(org.Hs.eg.db)
data(geneList, package="DOSE")
gene <- names(geneList)[abs(geneList) > 2]
gene.df <- bitr(gene, fromType = "ENTREZID",
                toType = c("ENSEMBL", "SYMBOL"),
                OrgDb = org.Hs.eg.db)
head(gene.df)
ego <- enrichGO(gene          = gene,
                universe      = names(geneList),
                OrgDb         = org.Hs.eg.db,
                ont           = "CC",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = TRUE);

head(ego)
emapplot(ego)

But the generated enrichment map missed edges. I don't know how to figure this problem out.
Hope for you answer.
Thank you!

**Comment by GuangchuangYu** [comment]
[duplicated](https://github.com/GuangchuangYu/enrichplot/issues/12).
