### ISSUE TITLE
bug in get_GO_data function

### ISSUE THREAD

**Issue by thongnt2** [GuangchuangYu/clusterProfiler#182]
I think there is a bug in the `get_GO_data` function in `enrichGO.R` script. In the code chunk below, the `GO2TERM` is never existed in `GO_Env` so the `use_cached` is always = FALSE. I removed the condition `exists("GO2TERM", envir=GO_Env, inherits=FALSE)` and it works. This helps speedup `enrichGO` a lot as I now can use catch data.

```  
    if (exists("organism", envir=GO_Env, inherits=FALSE) &&
        exists("keytype", envir=GO_Env, inherits=FALSE)) {

        org <- get("organism", envir=GO_Env)
        kt <- get("keytype", envir=GO_Env)

        if (org == get_organism(OrgDb) &&
            keytype == kt &&
            exists("goAnno", envir=GO_Env, inherits=FALSE) &&
            exists("GO2TERM", envir=GO_Env, inherits=FALSE)){

            use_cached <- TRUE
        }
    }
```

**Comment by GuangchuangYu** [comment]
thanks.
