### ISSUE TITLE
Issues of clusterprofiler development version installation

### ISSUE THREAD

**Issue by ChengYunazhi** [GuangchuangYu/clusterProfiler#19]
Hi, Guangchuang

all the depends packages of clusterProfiler is installed and can be used. but when I install the clusterProfiler, the R throw me this issues, as below:
![z7932 4vsznc 0sudhtl7](https://cloud.githubusercontent.com/assets/13846735/9324289/6d8a09ee-45bb-11e5-9c1a-3d64801b032e.png)

how can deal with this problem.

thanks!

**Comment by GuangchuangYu** [comment]
[dotplot](http://ygc.name/2015/06/23/dotplot-for-enrichment-result/) was introduced recently from user's request and was implemented in my `DOSE` package.

You are installing the devel branch of `clusterProfiler` with release branch of `DOSE`. This is the reason R throw this error.

Use `install_github(c("GuangchuangYu/DOSE", "GuangchuangYu/clusterProfiler"))` to install latest version of `clusterProfiler` as already presented in [README.md](https://github.com/GuangchuangYu/clusterProfiler/blob/master/README.md).

**Comment by GuangchuangYu** [comment]
In addition, Bioconductor is tied to specific R version. There may be other issues due to other out-of-date dependencies.

I recommend you upgrade your R to  3.2.2 and Bioconductor to latest release (3.1).
