### ISSUE TITLE
enrichKEGG returning NA

### ISSUE THREAD

**Issue by ralowe** [GuangchuangYu/clusterProfiler#20]
It appears that enrichKEGG is returning NA. This can be repeated using:
```r
data(gcSample)
yy = enrichKEGG(gcSample[[5]], pvalueCutoff=0.01)
print(yy)
```

**Comment by GuangchuangYu** [comment]
It's due to KEGGREST fail to fetch KEGG annotation.

```r
> KEGGREST::keggLink("hsa", "pathway")
character(0)
```

**Comment by ralowe** [comment]
Ok looks like http://rest.kegg.jp/link/hsa/pathway is down. http://rest.kegg.jp/link/pathway/hsa works though.

**Comment by GuangchuangYu** [comment]
You can use 

```r
yy = enrichKEGG(gcSample[[5]], pvalueCutoff=0.01, use_internal_data=TRUE)
```

to force `enrichKEGG` using `KEGG.db` which was not updated since 2012.

**Comment by GuangchuangYu** [comment]
[http://rest.kegg.jp/link/hsa/pathway](http://rest.kegg.jp/link/hsa/pathway) is back.

```r
> data(gcSample)
> yy = enrichKEGG(gcSample[[5]], pvalueCutoff=0.01)
> yy
929 human Genes to  KEGG  test for over-representation.
 with p value < 0.01
```
