### ISSUE TITLE
bitr, show genes not mapped...

### ISSUE THREAD

**Issue by jgarces02** [GuangchuangYu/clusterProfiler#209]
Hi  @GuangchuangYu, 

It's not properly an error -the package is wonderful itself!- but I missed a detail in `bitr` that could be useful: moreover of showing the percentage of non-mapped gene symbols, maybe pointing out what are those genes would be a perfect idea!

Thanks anyway for this package!

**Comment by GuangchuangYu** [comment]
in the condition that the un-mapped list is long, it is not friendly to print all of them.

You can just use `genes[!genes %in% bitr_result[,1]]` to print them.

**Comment by jgarces02** [comment]
Perfect. Thanks!
