### ISSUE TITLE
dotplot is duplicating x-axis labels

### ISSUE THREAD

**Issue by jgarces02** [GuangchuangYu/clusterProfiler#211]
Hi @GuangchuangYu, 

This time it's an error, maybe mine, I don't know. I've ran all analysis and created a _master_ table with them, some like this:
```
Cluster analysis                                 ID                        Description GeneRatio  BgRatio    pvalue  p.adjust    qvalue geneID Count
Plasm.  Hallmk.           HALLMARK_HEME_METABOLISM           HALLMARK_HEME_METABOLISM      1/17 200/4393 0.5477910 0.5514508 0.5482259  BLVRA     1
Plasm.  Hallmk.     HALLMARK_INFLAMMATORY_RESPONSE     HALLMARK_INFLAMMATORY_RESPONSE      1/17 201/4393 0.5496244 0.5514508 0.5482259   TLR3     1
Plasm.  Hallmk.                HALLMARK_COMPLEMENT                HALLMARK_COMPLEMENT      1/17 202/4393 0.5514508 0.5514508 0.5482259    CFH     1
CTCs       GO GO:0051015                        actin filament binding      3/16 174/17548 0.0004879708 0.03708578 0.02619633 SPTA1/IQGAP2/MYO5C     3
CTCs       GO GO:0071933                        Arp2/3 complex binding      1/16   9/17548 0.0081780558 0.11455930 0.08092139             IQGAP2     1
CTCs       GO GO:0004089                carbonate dehydratase activity      1/16  14/17548 0.0126942847 0.11455930 0.08092139                CA8     1
```
For this, I've combined `enrichGO` and `enricher` with `merge_results` and changed colnames manually to adjust `Cluster`.

The problem is `dotplot` is drawing a plot duplicating the x-axis labels, I guess because internally is considering each analysis individually in the plotting... moreover, it adds an additional NA column!

![image](https://user-images.githubusercontent.com/27858969/59457312-7b452880-8e18-11e9-893c-ba7c71aeed9d.png)

Another approximation I tried was do it through facets, but the error remains...

![image](https://user-images.githubusercontent.com/27858969/59457450-b3e50200-8e18-11e9-815a-d94dde8ad140.png)

Any idea what I'm missing, please?

**Comment by GuangchuangYu** [comment]
you need to provide reproducible example.

**Comment by jgarces02** [comment]
Solved, sorry for disturbing you. In some place changing manually colnames I did a mistake... maybe because I used two `merge_results`. 

Now its working perfectly. Thanks!
