### ISSUE TITLE
TAIR ID not working for Arabidopsis

### ISSUE THREAD

**Issue by huangty1208** [GuangchuangYu/clusterProfiler#22]
I tried TAIR ID for enrichGO and got the following message. 

Error in .testForValidKeys(x, keys, keytype) : 
None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.

I also tried the code you posted.

c= head(keys(org.At.tair.db))
[1] "AT1G01010" "AT1G01020" "AT1G01030" "AT1G01040" "AT1G01050" "AT1G01060"
and the result is the same. 
c
[1] "AT1G01010" "AT1G01020" "AT1G01030" "AT1G01040" "AT1G01050"
[6] "AT1G01060"
ego <- enrichGO(gene = c,
organism = "arabidopsis",
ont = "MF",
pAdjustMethod = "BH",
pvalueCutoff = 0.01,
qvalueCutoff = 0.05,
readable = TRUE)

Error in .testForValidKeys(x, keys, keytype) : 
None of the keys entered are valid keys for 'ENTREZID'. Please use the keys method to see a listing of valid arguments.

That's why I tried to use ENTREZ ID and got a N/A. 
Is there anything wrong with arabidopsis as a parameter?

**Comment by GuangchuangYu** [comment]
see [https://github.com/GuangchuangYu/clusterProfiler/issues/21](https://github.com/GuangchuangYu/clusterProfiler/issues/21).
