### ISSUE TITLE
Matching EntrezID with go term

### ISSUE THREAD

**Issue by adomingues** [GuangchuangYu/clusterProfiler#24]
Hi Guangchuang,

not really an issue, but more of a question (quite possibly related to DOSE). I am interested in creating a data.frame with my original data, which included entrezIDs, and add associated GO terms. Is there an easy/simple way of matching entrezIDs with the GO terms returned by clusterProfiler? 

For instance, when using `groupGO` the result (`summary(head(ggo))`) is a table with the GO_ID, description, (..), and geneID. However, as far as can see the geneID is the gene symbol, and not the input for `groupGO` (entrezID). The information currently returned by `groupGO` is very informative, but This makes it somewhat difficult to merge together with the original input.

The information seems to be in `ggo@geneInCategory`, and I am just wondering if there is a way of getting in a nice format. For instance (made up IDs):
> Entrez   GO
> 0065009 GO:0044085 regulation of transcription
> 0012890 GO:0019953 sexual reproduction
> (..)

This would be really helpful.

Cheers.

**Comment by GuangchuangYu** [comment]
By default, `readable=FALSE` and `clusterProfiler` will not convert geneID to symbol and you can match the output with associated info of your input easily.

To tidy the output in the format you mentioned above, you can use the following command:

```r
de=names(geneList)[geneList > 2]
x=groupGO(de, level=3)
stack(x@geneInCategory) -> go
clusterProfiler:::TERM2NAME.GO(unique(go[,2])) -> termname
go$desc = termname[go[,2]]
```

```
> head(go)
  values        ind
1   6280 GO:0005886
2   9833 GO:0005886
3   6279 GO:0005886
4   8685 GO:0005886
5   3627 GO:0005886
6   8140 GO:0005886
                                                           desc
1 nuclear outer membrane-endoplasmic reticulum membrane network
2 nuclear outer membrane-endoplasmic reticulum membrane network
3 nuclear outer membrane-endoplasmic reticulum membrane network
4 nuclear outer membrane-endoplasmic reticulum membrane network
5 nuclear outer membrane-endoplasmic reticulum membrane network
6 nuclear outer membrane-endoplasmic reticulum membrane network
```

**Comment by adomingues** [comment]
Cheers, that solved the problem.
