### ISSUE TITLE
gseGO: p-values and gseaplot

### ISSUE THREAD

**Issue by mevers** [GuangchuangYu/clusterProfiler#25]
Dear Guangchuang.

I have come across two issues, maybe you can clarify.

I perform a GSEA analysis within clusterProfiler using

`res.GSEA.GO<-gseGO(geneList = geneList,
                       organism = "human",
                       exponent = 1,
                       ont = "BP",
                       nPerm = 1000,
                       minGSSize = 15,
                       pvalueCutoff = 0.01,
                       verbose = TRUE);
`

1.) The resulting table of GO terms all seem to have the same p-values, adjusted p-values, and q-value. For example notice the entries in the last column (qvalues = 0.00470813780684201) :
> ID	Description	setSize	enrichmentScore	pvalue	p.adjust	qvalues
> GO:0000070	GO:0000070	mitotic sister chromatid segregation	104	0.183705167498055	0.000999000999000999	0.00691405858579111	0.00470813780684201
> GO:0000075	GO:0000075	cell cycle checkpoint	244	0.1685954733772	0.000999000999000999	0.00691405858579111	0.00470813780684201
> GO:0000077	GO:0000077	DNA damage checkpoint	152	0.189584910513727	0.000999000999000999	0.00691405858579111	0.00470813780684201
> GO:0000082	GO:0000082	G1/S transition of mitotic cell cycle	242	0.148857665664357	0.000999000999000999	0.00691405858579111	0.00470813780684201

The results are similar for other ontologies.

2.) All GSEA plots seem to have a discontinuity in the the "phenotype" curves. See e.g. here http://imgur.com/AcH49Bh . 

Any help in resolving these issues would be greatly appreciated.

Best,
Maurits

**Comment by GuangchuangYu** [comment]
can you send a sample data that can reproduce this issue to gcyu@hku.hk?

**Comment by mevers** [comment]
I send you a sample file & data to your email address.
Thanks,
Maurits

**Comment by GuangchuangYu** [comment]
This is due to your input `geneList` is not sorted. 
```r
geneList <- sort(geneList, decreasing = T)
```
will fix the issue.

I have updated the source code, so that if user input un-sorted `geneList`, it will stop and complain, see [https://github.com/GuangchuangYu/DOSE/commit/5a7bc077d72e03d451a02b197f01bf3905431a02](https://github.com/GuangchuangYu/DOSE/commit/5a7bc077d72e03d451a02b197f01bf3905431a02).

**Comment by mevers** [comment]
Dear Guangchuang.

Thanks for the quick update. Yes, this seems to fix the issue with the
constant p-values.
There still remains the issue with the discontinuities in the phenotype
correlation plots. See e.g. term GO:0000070 (attached).
Any advice?

Thanks,
Maurits

**Comment by GuangchuangYu** [comment]
Your `geneList` is weird with many values identical. This maybe the reason.

```
> table(geneList) %>% as.data.frame %>% subset(., Freq > 500)
   geneList Freq
54     0.86  526
56     0.88  534
58      0.9  584
60     0.92  570
62     0.94  528
66     0.98  522
68        1  506
```

**Comment by mevers** [comment]
Dear Guangchuang.

I'm sorry but that is a very poor excuse. The discontinuity of the phenotype correlation plots suggests to me that this is a numerical issue in your code. It looks like a branch cut in the function you use to plot the phenotype correlation curves that occurs if the values of the ranking metric are not distributed around zero.

Broad's GSEA-P does not seem to have this issue, so it is definitely not an issue with the data.

Best,
Maurits

**Comment by GuangchuangYu** [comment]
The weird thing is I couldn't replicate your issue. It shouldn't happened if your input `geneList` was sorted.

Can you save the object, `res.GSEA.GO`, to `rda` file and send to me?

**Comment by mevers** [comment]
Dear Guangchuang.

I did some more testing, and indeed the discontinuities in the phenotype plots have disappeared, following sorting of the ranked gene list. So all is well. Thanks for looking into this and your help.

Best regards,
Maurits
