### ISSUE TITLE
setting GO level in function compareClusters 

### ISSUE THREAD

**Issue by ahorvath** [GuangchuangYu/clusterProfiler#26]
Hi Guangchuang Yu,

It would be useful to set the level of the GO hierarchy in function compareClusters like in David GO analyser tool ("BP4" for example).

Because, sometimes the less specific gene sets involve too general terms.

Best Regards,
Attila Horvath

**Comment by GuangchuangYu** [comment]
You implemented a function, _dropGO_, that can be used to drop GO terms or specific level of GO terms.

see [https://github.com/GuangchuangYu/clusterProfiler/commit/48fcd02dd6ae5fe1522cefa7de317dc0ff135e24](https://github.com/GuangchuangYu/clusterProfiler/commit/48fcd02dd6ae5fe1522cefa7de317dc0ff135e24).

**Comment by GuangchuangYu** [comment]
@ahorvath FYI, restricted GO enriched result at specific level is now available, see [https://github.com/GuangchuangYu/clusterProfiler/issues/30](https://github.com/GuangchuangYu/clusterProfiler/issues/30).
