### ISSUE TITLE
reduce redundancy of enriched GO terms

### ISSUE THREAD

**Issue by GuangchuangYu** [GuangchuangYu/clusterProfiler#28]
To simplify the enriched result, we can use `slim` version of GO and use [enricher()](http://ygc.name/2015/05/11/use-clusterprofiler-as-an-universal-enrichment-analysis-tool/) function to analyze.

Another strategy is to use [GOSemSim](http://www.bioconductor.org/packages/GOSemSim) to calculate similarity of GO terms and remove those highly similar terms by keeping one representative term.

The criteria of selecting representative term can be:
+ most informative term (need pre-calculated IC data, only available for those internally supported organisms in `GOSemSim`; can be extended to un-supported organisms).
+ most significant term (as in [REVIGO](http://revigo.irb.hr/))

I prefer using the second criteria for it's more intuitive and more easy to implement for those not internally supported by `GOSemSim`.

I propose to define a function to `simplify` the output from `enrichGO` by removing redundant GO terms.

```r
simplify <- function(enrichResult, cutoff=0.7, by="p.adjust", select_fun=min) {
     ## GO terms that have semantic similarity higher than `cutoff` are treated as redundant terms
     ## select one representative term by applying `select_fun` to feature specifying by `by`.
     ## user can defined their own `select_fun` function.
     
     ## return an updated `enrichResult` object.
}
```

Any comment/suggestion is welcome.

### Reference:
+ [https://www.biostars.org/p/47672/](https://www.biostars.org/p/47672/)
+ [http://www.sciencedirect.com/science/article/pii/S0002929714002626](http://www.sciencedirect.com/science/article/pii/S0002929714002626)

**Comment by GuangchuangYu** [comment]
finished in [https://github.com/GuangchuangYu/clusterProfiler/commit/7e32c7d180ca928a22b58755d2949ad429c1e45f](https://github.com/GuangchuangYu/clusterProfiler/commit/7e32c7d180ca928a22b58755d2949ad429c1e45f)

I will close the issue. Comment is still welcome.

**Comment by GuangchuangYu** [comment]
output from _compareCluster_ is also supported, see[https://github.com/GuangchuangYu/clusterProfiler/commit/983262ba612ae827df0430f8f939c03b776190b1](https://github.com/GuangchuangYu/clusterProfiler/commit/983262ba612ae827df0430f8f939c03b776190b1).

**Comment by GuangchuangYu** [comment]
see also the [blog post](http://ygc.name/2015/10/21/use-simplify-to-remove-redundancy-of-enriched-go-terms/)

**Comment by Archieyoung** [comment]
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simplify’ for signature ‘"enrichResult"’

**Comment by fssdlyl001** [comment]
Hi, I applied simplify() function to compareCluster result, but return an error message: "Error in FUN(X[[i]], ...) : unused argument (organism = "human")". If I used enrichGO result as input, simplify worked. Could you help me solve this problem? Thank you.

**Comment by GuangchuangYu** [comment]
it was fixed in github version which will be released on Wednesday in BioC 3.4.

**Comment by fssdlyl001** [comment]
Thank you very much.

**Comment by fssdlyl001** [comment]
Thank you very much. Just one more question: which "semData" should I use for simpifying compareCluster results? If it needs to set manually, what's the default semData of simplify()?

**Comment by GuangchuangYu** [comment]
you need to refer to the [GOSemSim vignette](https://bioconductor.org/packages/devel/bioc/vignettes/GOSemSim/inst/doc/GOSemSim.html). 

If you use measure = 'Wang', you don't need to pass `semData`.

**Comment by fssdlyl001** [comment]
But when I run simplify(x, measure="Wang"), it also return an message: _Error in FUN(X[[i]], ...) : argument "semData" is missing, with no default_. If I add 'semData = NULL', I got _Error in match.arg(ont, c("BP", "CC", "MF")) : 'arg' must be of length 1_. Where did I go wrong?

**Comment by GuangchuangYu** [comment]
```r
data(gcSample)
x = compareCluster(gcSample, fun='enrichGO', ont='MF', OrgDb='org.Hs.eg.db')
y <- simplify(x, measure='Wang', semData=NULL) 
```

works.


pls follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/) and provide a reproducible example.

**Comment by tigerxu** [comment]
Hi, I applied the simplify() function to reduce redundancy of the enriched GO terms produced by enrichGO. The codes below runs fine without error. But I noticed that several redundant GO terms were not filtered out. The example is below

genedata <- read.table("genedata.txt", quote=NULL, header=TRUE, check.names=F, sep="\t")
head(genedata)
eg = bitr(genedata$`Protein IDs`, fromType="UNIPROT", toType="ENTREZID", OrgDb="org.Hs.eg.db")
egobp <- enrichGO(gene          = eg$ENTREZID,
                  OrgDb         = org.Hs.eg.db,
                  ont           = "BP",
                  pAdjustMethod = "BH",
                  pvalueCutoff  = 0.01,
                  qvalueCutoff  = 0.01,
                  readable      = TRUE)
egobp2 <- simplify(egobp, cutoff=0.6, by="p.adjust", select_fun=min)
head(egobp2)

I show the first six GO terms below
           Count
GO:0006335    24
GO:0034723    24
GO:0045861    64
GO:0051290    25
GO:0000183    24
GO:0002576    36

I compared the similarity of GO terms using GOSemSim and the result is as follows
> goSim("GO:0006335", "GO:0034723", semData=hsGObp, measure="Jiang")
[1] 1
> goSim("GO:0006335", "GO:0034723", semData=hsGObp, measure="Wang")
[1] 0.671

It looks that one of "GO:0006335" and "GO:0034723" should be filtered but actually not. Can you help to look at this problem? Any advice is very appreciated.

Thanks for developing clusterProfiler!

Zhuofei Xu

**Comment by GuangchuangYu** [comment]
pls follow <https://guangchuangyu.github.io/2016/07/how-to-bug-author/> and provide a reproducible example.

**Comment by msquatrito** [comment]
Hi,
I've been trying to use the `simplify` function and I'had similar issue to @tigerxu. I've realised that in my case the problem was due to the fact that GO terms with the same "p.adjust" are not filtered out.
I've solved it using `simplify(..., by = "pvalue")`. 
Best,
Massimo

**Comment by tigerxu** [comment]
thanks for sharing this info, Massino! I will try again. 
Zhuofei

**Comment by hmontenegro** [comment]
Doesn't `simplify` work with gseaResult objects?

`cc.simp <- simplify( ego.cc, cutoff = 0.7, by = "p.adjust", select_fun = min )`

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘simplify’ for signature ‘"gseaResult"’

**Comment by haiyueliu** [comment]
Hi, 

I am using simplify function, but it comes to errors.
> ego2_52_slim <- simplify(ego2_52, cutoff=0.7, by="p.adjust", select_fun=min)
Error in .local(x, ...) : 
  simplify only applied to output from enrichGO...

I am sure the input is result from enrichGO. Could you please help me to have a look of this?

And also, you mentioned that you prefer using the second criteria which is "REVIGO", but here in simplify, you integrated GOSemSim, right?.

Thanks,
Haiyue

**Comment by zh542370159** [comment]
@haiyueliu I have the same problem. I guess it occurs because I installed the enrichplot?

**Comment by Lucyyang1991** [comment]
It takes me really long time to run the _simplify_ function, it that normal?

**Comment by sjidong12** [comment]
I have a similar problem with "Lucyyang1991". It takes quite long time to run the simplify function. Is that normal?

**Comment by davemcg** [comment]
`simplify` does not work with `enrichGO` output if the ontology used is "ALL"

**Comment by steffenheyne** [comment]
same here...also when I don't use "ALL" but like ont="BP" , simplify never finishes for me

**Comment by VictorGoitea** [comment]
the same... ont="BP", simplify never finishes for me

**Comment by steffenheyne** [comment]
actually the problem seems to be that now (was there a change?) eg. enrichGO() returns an object that stores in ego@result also all unsignificant results. When I strip this down to the sig.-only results 
by eg.:

`ego@result[ego@result$qvalue<=ego@qvalueCutoff,]`

simplify finishes normally. But I don't know if the result of simplify is still correct with that change.
@GuangchuangYu ?

I just also strip down `ego@geneSets = data.frame()` as the result df contains all the genesets. With that I get a much smaller objects. But I think this is not used by simplify at all.

**Comment by GuangchuangYu** [comment]
@steffenheyne thanks for pointing this out. Yes, the result should be strip down before simplify. Will fix it.

**Comment by VictorGoitea** [comment]
Thanks Steffen! Your suggestion worked perfect.

**Comment by xxz19900** [comment]
> `simplify` does not work with `enrichGO` output if the ontology used is "ALL"

Have you solved this problem? I also encountered such condition.

**Comment by steffenheyne** [comment]
@xxz19900 simplify only works within a sub-ontology like BP, MF or CC, not with `ont= 'ALL'`, like 
```
x  <- enrichGO(dat, ont = 'BP', OrgDb = 'org.Hs.eg.db')
y <- simplify(x)
```

**Comment by kamalmdmostafa** [comment]
> @xxz19900 simplify only works within a sub-ontology like BP, MF or CC, not with `ont= 'ALL'`, like
> 
> ```
> x <- enrichGO(dat, ont = 'BP', OrgDb = 'org.Hs.eg.db')
> y <- simplify(x)
> ```

I am having error when using the above code for simplifying Arabidopsis GO BP data. 

> x <- enrichGO(earlyresponse, ont = 'BP', keyType = "TAIR", OrgDb = 'org.At.tair.db')
> y <- simplify(x)
Error in as.list.default(X) : 
  no method for coercing this S4 class to a vector


Also seeing the following error with the other approach: 

simplify(egoBP_earlyresponse, pvalueCutoff = 0.7, select_fun=min)
Error in simplify(egoBP_earlyresponse, pvalueCutoff = 0.7, select_fun = min) : 
  unused arguments (pvalueCutoff = 0.7, select_fun = min)

Any suggestions will be helpful. I am not an expert in R.

**Comment by kamalmdmostafa** [comment]
I am seeing the following error when using simplify() function for my Arabidopsis GO BP data: 

> egoBP_earlyresponse <- enrichGO(gene = earlyresponse,
+                                 universe = allOE_genes,
+                                 keyType = "TAIR",
+                                 OrgDb = org.At.tair.db, 
+                                 ont = "BP", 
+                                 pAdjustMethod = "BH", 
+                                 pvalueCutoff= 0.01,
+                                 qvalueCutoff = 0.05,
+                                 readable = FALSE)
> 
> cluster_summaryBP_earlyresponse <- data.frame(egoBP_earlyresponse)

#simplify 
> simplify(egoBP_earlyresponse, pvalueCutoff = 0.7, select_fun=min)
Error in simplify(egoBP_earlyresponse, pvalueCutoff = 0.7, select_fun = min) : 
  unused arguments (pvalueCutoff = 0.7, select_fun = min)


Any suggestions will be helpful. I am not an expert in R.

**Comment by kamalmdmostafa** [comment]
I am having the following error when trying to simplify Arabidopsis GO BP data: 

> egoBP_earlyresponse <- enrichGO(gene = earlyresponse,
+                                 universe = allOE_genes,
+                                 keyType = "TAIR",
+                                 OrgDb = org.At.tair.db, 
+                                 ont = "BP", 
+                                 pAdjustMethod = "BH", 
+                                 pvalueCutoff= 0.01,
+                                 qvalueCutoff = 0.05,
+                                 readable = FALSE)
> 
> cluster_summaryBP_earlyresponse <- data.frame(egoBP_earlyresponse)
> #simplify
> 
> simplify(egoBP_earlyresponse, cutoff = 0.7, by = "p.adjust", select_fun=min)
Error in simplify(egoBP_earlyresponse, cutoff = 0.7, by = "p.adjust",  : 
  unused arguments (cutoff = 0.7, by = "p.adjust", select_fun = min)


Any suggestion will be appreciated .

**Comment by Coke-Zhang** [comment]
> `simplify` does not work with `enrichGO` output if the ontology used is "ALL"

If your cutoff is same among the three ontology, you can use simplify_internal(res, cutoff=0.7, by="p.adjust", 
                      select_fun=min, measure="Wang", ontology='BP', semData), in which must pass the one of three ontology parameters, the results is same. The function can reduce redundancy of three ontology.
code from https://github.com/YuLab-SMU/clusterProfiler/issues/162

simplify_internal <- function(res, cutoff=0.7, by="p.adjust", select_fun=min, measure="Rel", ontology, semData) {
  if (missing(semData) || is.null(semData)) {
    if (measure == "Wang") {
      semData <- GOSemSim::godata(ont = ontology)
    } else {
      stop("godata should be provided for IC-based methods...")
    }
  } else {
    if (ontology != semData@ont) {
      msg <- paste("semData is for", semData@ont, "ontology, while enrichment result is for", ontology)
      stop(msg)
    }
  }
  
  sim <- GOSemSim::mgoSim(res$ID, res$ID,
                semData = semData,
                measure=measure,
                combine=NULL)
  
  ## to satisfy codetools for calling gather
  go1 <- go2 <- similarity <- NULL
  
  sim.df <- as.data.frame(sim)
  sim.df$go1 <- row.names(sim.df)
  sim.df <- tidyr::gather(sim.df, go2, similarity, -go1)
  
  sim.df <- sim.df[!is.na(sim.df$similarity),]
  
  ## feature 'by' is attached to 'go1'
  sim.df <- merge(sim.df, res[, c("ID", by)], by.x="go1", by.y="ID")
  sim.df$go2 <- as.character(sim.df$go2)
  
  ID <- res$ID
  
  GO_to_remove <- character()
  for (i in seq_along(ID)) {
    ii <- which(sim.df$go2 == ID[i] & sim.df$similarity > cutoff)
    ## if length(ii) == 1, then go1 == go2
    if (length(ii) < 2)
      next
    
    sim_subset <- sim.df[ii,]
    
    jj <- which(sim_subset[, by] == select_fun(sim_subset[, by]))
    
    ## sim.df <- sim.df[-ii[-jj]]
    GO_to_remove <- c(GO_to_remove, sim_subset$go1[-jj]) %>% unique
  }
  
  res[!res$ID %in% GO_to_remove, ]
}

**Comment by laijen000** [comment]
Hi Dr. Yu, 

I would like to use GOSemSim to select the most informative term when comparing lists of GO IDs using mgoSim(). I am using the mouse genome and calculated IC scores: mmGO <- godata('org.Mm.eg.db', ont='BP'). 
Once we obtain the similarity matrix, is there a way to filter it to select just the most informative term above a certain similarity cutoff? 

Because my GO IDs are not from using enrichGO, I am unable to use the simplify function. So I would like to try GOSemSim instead. Thank you!

**Comment by claraina** [comment]
I am having the same problem with @kamalmdmostafa, getting the error "unused arguments (cutoff = 0.7, by = "p.adjust", select_fun = min)" even though it seems to work with another set of genes. I don't think it's an issue with my enrich object (ego) as it is still showing the relevant GO Terms. 

EEDDOC_ego <- enrichGO(gene          = EEDDOC_gene.df$ENTREZID,
                OrgDb         = org.Mm.eg.db,
                keyType = 'ENTREZID',
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                qvalueCutoff  = 0.05,
        readable      = TRUE)

sEEDDOC_ego <- simplify(EEDDOC_ego, cutoff=0.7, by="p.adjust", select_fun = min)

**Comment by kamalmdmostafa** [comment]
@claraina could you solve this issue. Seems like they gave up on this issue. Any other way to solve this? Creating a new issue maybe?

**Comment by huerqiang** [comment]
@kamalmdmostafa  https://github.com/YuLab-SMU/clusterProfiler/issues/278

**Comment by huerqiang** [comment]
@kamalmdmostafa  https://github.com/YuLab-SMU/clusterProfiler/issues/278

**Comment by TylerSagendorf** [comment]
> Hi, I love the clusterprofiler package and regularly use the gseaGO and gseaKEGG functions to investigate my scRNAseq experiment results. However, using these there is always the problem of having many related terms enriched. Would it be possible to implement a function that only selects the most specific term that is enriched in the result for visualization in the dotplot() function? And/or extend the simplify function to work on gsea objects?
> 
> Best, Niko

Hi Niko, here is some code that selects the most general term: https://github.com/YuLab-SMU/clusterProfiler/issues/372

If you instead compute `last_GO_level = unlist(lapply(GO_levels, max))` and then use 

`x <- simplify(x, cutoff = 0.7, by = "last_GO_level", select_fun = max)`,

you will get the most specific enriched terms. 

**If you are not looking for the most specific terms and just want to deal with the redundancy issue**, use the [msigdbr](https://cran.r-project.org/web/packages/msigdbr/index.html) package to obtain **non-redundant gene sets/pathways**. Then, supply them to `clusterProfiler::GSEA` or `fgsea::fgsea` to perform FGSEA.

**Comment by TylerSagendorf** [comment]
> hi @TylerSagendorf you mentioned in your post at the end that i can obtain non-redundant gene-sets/pathways directly from misgdbr? but i couldn't find a specific function which allows me to download non-redundant GO BP or GO CC genesets. Unless , the genesets on MSigDB are non redundant already ?

The gene sets/pathways provided by MSigDB on their [website](http://www.gsea-msigdb.org/gsea/msigdb/index.jsp) and through the msigdbr package are non-redundant. They explain how GO terms are filtered in the [v7.0 release notes](https://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/MSigDB_v7.0_Release_Notes#:~:text=This%20procedure%20has,GO%20ontology%20tree). I only know for sure that the same type of procedure is applied to Reactome pathways, but they claim that the entire database has had its redundancy decreased (doi: [10.1016/j.cels.2015.12.004](https://dx.doi.org/10.1016%2Fj.cels.2015.12.004)).

**Comment by TylerSagendorf** [comment]
@deevdevil88 No problem! Glad I could help.
