### ISSUE TITLE
facet compareCluster result

### ISSUE THREAD

**Issue by GuangchuangYu** [GuangchuangYu/clusterProfiler#32]
This is an idea from @dalloliogm 

>
>it would be better if compareCluster would return a dataframe with multiple columns, instead of merging them into a single column called Cluster. This would be make it possible to plot the results using facets or something more fancy.

see [http://bioinfoblog.it/2015/02/a-formula-interface-for-geneontology-analysis/](http://bioinfoblog.it/2015/02/a-formula-interface-for-geneontology-analysis/).

```{r}
data(geneList, package="DOSE")
mydf <- data.frame(Entrez=names(geneList), FC=geneList)
mydf <- mydf[abs(mydf$FC) > 1,]
mydf$group <- "upregulated"
mydf$group[mydf$FC < 0] <- "downregulated"
mydf$othergroup <- "A"
mydf$othergroup[abs(mydf$FC) > 2] <- "B"

require(clusterProfiler)
xx <- compareCluster(Entrez~group+othergroup, data=mydf, fun="enrichGO")
require(ggplot2)
## plot(xx), since the parameter x was already taken as input object, we can use `x` to specify x variable.
## now we prefer using `dotplot` function to produce the same figure.
dotplot(xx)
```
![screenshot 2015-11-03 19 13 06](https://cloud.githubusercontent.com/assets/626539/10906775/209c6d4e-825f-11e5-82e1-38d04f44ec4a.png)

```r
## now we can specify other x variable instead of the default `Cluster` variable.
dotplot(xx,x=~group) + facet_grid(~othergroup)
```
![screenshot 2015-11-03 19 08 31](https://cloud.githubusercontent.com/assets/626539/10906804/710548c8-825f-11e5-8eb0-1ee598d96898.png)

**Comment by GuangchuangYu** [comment]
see [https://github.com/GuangchuangYu/clusterProfiler/commit/a8fe7b9c40f78482e18f51e58ff632a86aa5f50a](https://github.com/GuangchuangYu/clusterProfiler/commit/a8fe7b9c40f78482e18f51e58ff632a86aa5f50a).

**Comment by dalloliogm** [comment]
I think it is much better now, thank you for implementing it :-)

**Comment by Psequencer** [comment]
Dear @GuangchuangYu , 
i have a group list as below:
`GO <- list(Stage_I=gene.list_I$ENTREZID,Stage_II=gene.list_II$ENTREZID,Stage_III=gene.list_III$ENTREZID,Stage_I=gene.list_IV$ENTREZID)`
`ComGO <- compareCluster(geneCluster = GO, fun = "enrichKEGG",organism="hsa") `

the example code as `(dotplot(xx,x=~group) + facet_grid(~othergroup))` is a little bit confusing for me, how can i change it for my groups and have separate columns?

**Comment by huerqiang** [comment]
@Psequencer  
```r
dotplot(ComGO)
```

**Comment by Psequencer** [comment]
> 
> 
> @Psequencer
> 
> ```r
> dotplot(ComGO)
> ```

Dear huerqiang , 
i don't want my plot be like this
[https://cloud.githubusercontent.com/assets/626539/10906775/209c6d4e-825f-11e5-82e1-38d04f44ec4a.png](url)
 
actually this is the kind of plot i want
[https://i.ibb.co/f2PSDRf/Rplot01.png](url)

thank you kindly

**Comment by huerqiang** [comment]
@Psequencer What(which column of your compareCluster result) do you want to use for the facet? In your example, you may not be able to find the suitable column.

**Comment by Psequencer** [comment]
> 
> 
> @Psequencer What(which column of your compareCluster result) do you want to use for the facet? In your example, you may not be able to find the suitable column.
i want to show my results in separate columns as stage_I to IV, not in one plot which i got early, based on my groups what do you suggest?

**Comment by chainorato** [comment]
Hi, I am unsure whether I should continue to post here.
However, I tried to follow this example and I found that using facets makes the number of genes in the cluster (the number in parentheses) disappear. 

Are there any ways to add the number of genes in the cluster to the facet plot?

Here is the command I used (in the loop). I wonder whether the number in parentheses is related to the $Cluster in compareClusterResult or not.

dotplot(CPfile, x="Category", showCategory=j, font.size=24, label_format=100) + ggtitle(title_name) + theme(plot.title=element_text(face="bold", size=24), legend.title=element_text(size=24), legend.text=element_text(size=20), axis.text.x=element_text(angle=90, vjust=0.5, hjust=1), strip.text.x=element_text(size=24)) + guides(size=guide_legend(order=1), colour=guide_colourbar(order=2, reverse=TRUE)) + facet_grid(~group)

![image](https://user-images.githubusercontent.com/32287948/214219105-82f9bb9b-0dc9-4914-a062-1c81aa2a9aab.png)
