### ISSUE TITLE
compareCluster: List all the enrichKEGG results?

### ISSUE THREAD

**Issue by xphab** [GuangchuangYu/clusterProfiler#33]
Dear Guangchuang,

Thanks for your great works for this helpful package.

I tried the "compareCluster" command with fun='enrichKEGG'. 
I input 2 samples, while got 1 results (compared results, that make sense). 

    cp = list(a.gene=a[,1], b.gene=b[,1]) 
    xx <- compareCluster(cp, fun="enrichKEGG", organism="syz", pvalueCutoff=1)
    plot(xx)

I wonder if I could get 2 results, and then I could plot them in one figure with dotplot(xx).
I mean I can run enrichKEGG() twice (one for a[,1], one for b[,1]) and plot the 2 results with dots in 2 figures. Could I dotplot the 2 results in one figure, like your example:

    xx.formula <- compareCluster(Entrez~group, data=mydf, fun='enrichKEGG')
    plot(xx.formula)

I wish you can understand what i mean for my poor english. Thanks again!
Best wishes,
Peng

**Comment by GuangchuangYu** [comment]
yes, it's possible.

With the example posted in [https://github.com/GuangchuangYu/clusterProfiler/issues/32](https://github.com/GuangchuangYu/clusterProfiler/issues/32):

```r
 dotplot(xx, x=~Count) + facet_grid(~Cluster)
```

will generate the following figure:
![screenshot 2015-11-12 11 30 21](https://cloud.githubusercontent.com/assets/626539/11109901/c7a86bb0-8930-11e5-9100-92ec1407f0bb.png)

**Comment by xphab** [comment]
Thx a lot! I will try it!

**Comment by GuangchuangYu** [comment]
Another example:

```r
dotplot(xx, x=~Count) + facet_grid(othergroup~group)
```

![screenshot 2015-11-12 11 42 06](https://cloud.githubusercontent.com/assets/626539/11110065/716d7950-8932-11e5-9c03-077fd9a37c57.png)

**Comment by xphab** [comment]
Thx a looooooooooooooooooooooooot!!!!

**Comment by xphab** [comment]
Hi Guangchuang,

  dotplot(xx, x=~Count) + facet_grid(othergroup~group)  Error in
.local(object, ...) : unused argument (x = ~Count)


when i follow the example in #32.. any idea please?
Thank you!

2015-11-12 11:42 GMT+08:00 Guangchuang Yu <notifications@github.com>:

> Another example:
>
> dotplot(xx, x=~Count) + facet_grid(othergroup~group)
>
> [image: screenshot 2015-11-12 11 42 06]
> <https://cloud.githubusercontent.com/assets/626539/11110065/716d7950-8932-11e5-9c03-077fd9a37c57.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GuangchuangYu/clusterProfiler/issues/33#issuecomment-155987755>
> .
>



-- 
Shenzhen Key Laboratory of Marine Biological Resources
and Ecological Environment
College of Life Sciences, Shenzhen University
518060, Shenzhen, China
E-mail: googneed@gmail.com
Tel: +86 15827609557

**Comment by GuangchuangYu** [comment]
you should install the dev branch of `clusterProfiler`:

```r
devtools::install_github(c("hadley/ggplot2", "GuangchuangYu/DOSE", "GuangchuangYu/clusterProfiler"))
```

**Comment by xphab** [comment]
i use rstudio, and it showed that error:
and when i use sudo rstudio, it works well!

Thanks again!
Best wishes,
Peng

2015-11-12 13:42 GMT+08:00 Guangchuang Yu <notifications@github.com>:

> you should install the dev branch of clusterProfiler:
>
> devtools::install_github(c("hadley/ggplot2", "GuangchuangYu/DOSE", "GuangchuangYu/clusterProfiler"))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GuangchuangYu/clusterProfiler/issues/33#issuecomment-156008078>
> .
>



-- 
Shenzhen Key Laboratory of Marine Biological Resources
and Ecological Environment
College of Life Sciences, Shenzhen University
518060, Shenzhen, China
E-mail: googneed@gmail.com
Tel: +86 15827609557
