### ISSUE TITLE
Can't install latest version of clusterProfiler from github

### ISSUE THREAD

**Issue by spleonard1** [GuangchuangYu/clusterProfiler#38]
Thanks for your quick response to my feature request for KEGG module enrichment!  I'm eager to try it out, but I keep getting a weird error when trying to install from github, and the install fails.  Any ideas?
Error : object ‘aes_’ is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package ‘clusterProfiler’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/clusterProfiler’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/clusterProfiler’
Error: Command failed (1)

full output:
> install_github(c("GuangchuangYu/DOSE", "GuangchuangYu/clusterProfiler"))
Downloading GitHub repo GuangchuangYu/DOSE@master
Installing DOSE
Skipping 2 packages not available: DO.db, GO.db
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  '/private/var/folders/g4/nw8h4p2556j6cxd22t9sb4b40000gn/T/RtmpqefDxc/devtools103906771e42f/GuangchuangYu-DOSE-9214bcc'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

* installing *source* package ‘DOSE’ ...
** R
** data
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]
[13]
[14]
[15]
[16]
[17]
[18]
[19]
[20]
[21]
[22]
[23]
[24]
[25]
[26]
[27]
[28]
[29]
Warning: replacing previous import by ‘graph::.__C__dist’ when loading ‘topGO’
** installing vignettes
** testing if installed package can be loaded
* DONE (DOSE)
Downloading GitHub repo GuangchuangYu/clusterProfiler@master
Installing clusterProfiler
Skipping 2 packages not available: DO.db, GO.db
Skipping 1 packages ahead of CRAN: DOSE
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore CMD INSTALL  \
  '/private/var/folders/g4/nw8h4p2556j6cxd22t9sb4b40000gn/T/RtmpqefDxc/devtools103906ccfd4d0/GuangchuangYu-clusterProfiler-b5abcdc'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library'  \
  --install-tests 

* installing *source* package ‘clusterProfiler’ ...
** R
** data
** inst
** preparing package for lazy loading
Error : object ‘aes_’ is not exported by 'namespace:ggplot2'
ERROR: lazy loading failed for package ‘clusterProfiler’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/clusterProfiler’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/clusterProfiler’
Error: Command failed (1)

Session Info:
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] BiocInstaller_1.20.1 ggplot2_1.0.1        devtools_1.9.1      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2      digest_0.6.8     MASS_7.3-45      grid_3.2.2       R6_2.1.1        
 [6] plyr_1.8.3       gtable_0.1.2     magrittr_1.5     scales_0.3.0     httr_1.0.0      
[11] stringi_1.0-1    reshape2_1.4.1   curl_0.9.4       rstudioapi_0.3.1 proto_0.3-10    
[16] tools_3.2.2      stringr_1.0.0    munsell_0.4.2    colorspace_1.2-6 memoise_0.2.1   
[21] knitr_1.11

**Comment by GuangchuangYu** [comment]
```r
Error : object ‘aes_’ is not exported by 'namespace:ggplot2'
```

obviously, you need to install github version of `ggplot2`.

**Comment by spleonard1** [comment]
Ha- yes, clearly.  All fixed- thanks, again!
