### ISSUE TITLE
too many GO enrichment result compared with amigo2 

### ISSUE THREAD

**Issue by zhidongzhu** [GuangchuangYu/clusterProfiler#42]
Hi, Dr Yu:

thanks a lot for you very useful software clusterPorfiler.

I compare the GO enrichment result from clusterProfiler and amigo2， and I find total result occured（221） in clusterprofiler outcome，and more results occured（522） in clusterprofiler’s。
why clusterProfiler obtained much more results of GO enrichmeng。

**Comment by GuangchuangYu** [comment]
follow the <http://guangchuangyu.github.io/2015/11/comparison-of-clusterprofiler-and-gsea-p/> and make sure you are using same inputs (both gene list and GO). If the problem still exists, provide a reproducible example here.

BTW: enrichGO is consistent with [GeneAnswers](http://guangchuangyu.github.io/2014/08/why-clusterprofiler-fails/) and GOstats.
