### ISSUE TITLE
'enricher' genric enrichment function

### ISSUE THREAD

**Issue by hooperj** [GuangchuangYu/clusterProfiler#45]
This function, for calculating enrichment of customized term/gene sets, is mentioned in the clusterProfiler documentation manual. I do not find it in the version installed from bioconductor, but do find it installing your latest version from github.
> install_github(c("GuangchuangYu/DOSE", "GuangchuangYu/clusterProfiler"))
>library(clusterProfiler)
>help(enricher)

My problem is with the custom genesets. I built a dataframe of 17 genesets with the pathway name in the first column and the gene symbol in the 2nd column:
>str(Term2Gene)
     'data.frame':	2485 obs. of  2 variables:
      $ Pathway    : chr  "Bmp" "Bmp" "Bmp" "Bmp" ...
      $ Gene.symbol: chr  "Acvr1" "Acvr2a" "Acvr2b" "Acvrl1" ...
>head(Term2Gene)
       Pathway Gene.symbol
     1     Bmp       Acvr1
     2     Bmp      Acvr2a
     3     Bmp      Acvr2b
     4     Bmp      Acvrl1

>table(Term2Gene$Pathway)
       AdhGPCR     Axon      Bmp     Cams clefting Cytokine  ECM2FAC    Eicos      Fgf 
                   78      198        141        166      568         200            231          42       78 
        GPCR       Hh    Hippo    Notch       RA      RTK  stretch      Wnt 
              271       71       48       58       24       91       54      166

When I run enricher on a test vector of 65 gene symbols, it finds one pathway enriched. But only 13 of my 17 genesets are in the result. When I run another test vector, it finds 16 of the 17 genesets. In both cases, the largest geneset ('clefting') is missing. Does this indicate that the missing genesets are not tested for enrichment? Or does it indicate some other problem? I'm attaching the Term2Gene dataframe FYI.
[Term2Gene.txt](https://github.com/GuangchuangYu/clusterProfiler/files/190981/Term2Gene.txt)

>Enblack <-enricher(genes, pvalueCutoff = 0.05, pAdjustMethod = "BH", qvalueCutoff = 1,
         universe=unique(unlist(Term2Gene$Gene.symbol)), TERM2GENE=Term2Gene )
>names(Enblack@geneSets)
      [1] "AdhGPCR"  "Axon"     "Bmp"      "Cams"     "Cytokine" "ECM2FAC"  "Fgf"     
      [8] "GPCR"     "Hh"       "Hippo"    "RTK"      "stretch"  "Wnt"

**Comment by GuangchuangYu** [comment]
It only test gene set size between [minGSSize, maxGSSize]. The default value of `maxGSSize` is 500.

You need to set `maxGSSize=NA` if you don't want to restrict the test with maximum gene set size.

**Comment by hooperj** [comment]
Thanks for the tip on Max geneset size. Actually, I’m still having a little trouble with ‘enricher’ error out on some modules.

'Error in data.frame(numWdrawn = k - 1, numW = M, numB = N - M, numDrawn = n) :
  arguments imply differing number of rows: 1, 0 ‘

I’ve got 18 custom genesets and a ton of ‘background' genes that I’ve defined as ‘other’ in my ‘Term2Gene' data frame.
And a list of modules ('modules3.4’), keyed by color, with the genes in each module  as modules3.4[[n]]$genes
I get that error whenever a module intersects only one of those genesets. I wrote a function that filter those out, to make the code run. But I would like those modules represented in the output. Am I missing something?

processModule <- function( modules, Term2Gene, qval_cutoff){

    # iterate through module colors (except grey), passing $genes to enricher function
    colors <- names(modules)[-which(names(modules) %in% c('grey', 'hclustOrder'))]
    # eliminate those with genes in only one pathway
    temp <- sapply(colors, function(color)
        length(unlist(sapply(unique(Term2Gene$Pathway)[1:18], function(path) intersect (Term2Gene$Gene.symbol[which(Term2Gene$Pathway ==path)], modules[[color]]$genes)), use.names = F))
        )
    onesies <- colors[which(temp == 1)]
    colors <- colors[which(temp >1)]

    clusterEnriched <-  sapply(colors, function(x)
                enricher(modules[[x]]$genes, pvalueCutoff = 0.5, pAdjustMethod = "BH",
                    qvalueCutoff = qval_cutoff, minGSSize=3, maxGSSize =600,
                    universe=unique(Term2Gene$Gene.symbol), TERM2GENE=Term2Gene )
                )
    }
test <- processModule(modules3.4,Term2Gene, 0.05)



joan

**Comment by GuangchuangYu** [comment]
this issue was removed several days ago and you need to install the github version of DOSE.

**Comment by hooperj** [comment]
THANKS!!! that took care of it.
On Apr 13, 2016, at 11:14 PM, Guangchuang Yu <notifications@github.com<mailto:notifications@github.com>> wrote:


this issue was removed several days ago and you need to install the github version of DOSE.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/GuangchuangYu/clusterProfiler/issues/45#issuecomment-209764993>

Joan Hooper
UCD School of Medicine
Dept. Cell & Developmental Biology
12801 E 17th Ave
L18-12103, MS 8108
Aurora, CO 80045
