### ISSUE TITLE
missing functions

### ISSUE THREAD

**Issue by aprice26** [GuangchuangYu/clusterProfiler#47]
Hi Guangchuang,

This may be something simple I'm not getting, but I loaded clusterProfiler from bioconductor and it seems to be missing functions included in the manual and vignette. For instance, dropGO(), dotplot(), and plotGOgraph() aren't recognized. Other functions, like enrichGO() or compareCluster(), work fine. Is there something I'm missing?

Thanks,

Amanda

**Comment by GuangchuangYu** [comment]
see <https://github.com/GuangchuangYu/ggtree/wiki/FAQ#could-not-find-function>

**Comment by aprice26** [comment]
I updated my version of R and that solved the issue. Thanks!

**Comment by liezeltamon** [comment]
Hi Guangchang,

I cannot use the function viewKEGG. I am using the latest R (3.5.2) and clusterProfiler_3.10.1. 

Best,
Liezel
