### ISSUE TITLE
newbie question on gseGO input gene list ranking

### ISSUE THREAD

**Issue by vsvinti** [GuangchuangYu/clusterProfiler#48]
Hi there

I am trying to run this with a list of genes and Pvalues. The manual says the input is "order ranked geneList". I thought that the ranking needs to have the most significant gene at the top, etc, but this gives me the following error:

Error in gseAnalyzer(geneList = geneList, setType = ont, organism = organism,  : 
  geneList should be a decreasing sorted vector..

Is the idea to have the genes ranked in decreasing Pvalue (least significant at the top)? The geneList example from DOSE has expression values, rather the Pvalues. 

Please advise, and thanks!
Vicky

**Comment by GuangchuangYu** [comment]
you can use p-score=-10log(pvalue), then smaller pvalues will have bigger p-scores.

**Comment by GuangchuangYu** [comment]
BTW: if you have further question, please post in https://groups.google.com/forum/#!forum/clusterprofiler
