### ISSUE TITLE
My "geneCluster"  works fine with "compareCluster" while using with "fun = "enrichGO" but not with "fun = "enrichKEGG""

### ISSUE THREAD

**Issue by ajeetmandal** [GuangchuangYu/clusterProfiler#50]
My "geneCluster = genes" works fine with function "compareCluster" using "fun = "enrichGO" to create an object while  if I used "fun = "enrichKEGG"" instead, it spits an error. Please see below:
`compGO <- compareCluster(geneCluster   = genes, 
                           fun           = "enrichGO",
                           pvalueCutoff  = 0.05, 
                           pAdjustMethod = "BH")`
give the following error:

`Error in `row.names<-.data.frame`(`*tmp*`, value = c(NA_character_, NA_character_,  : 
  duplicate 'row.names' are not allowed
In addition: There were 50 or more warnings (use warnings() to see the first 50)`
Could you please help on this issue?
Thanks in advance,
Ajeet

**Comment by GuangchuangYu** [comment]
please follow the [guidelines](https://github.com/GuangchuangYu/clusterProfiler/blob/master/CONTRIBUTING.md)  and post a reproducible example.

**Comment by ajeetmandal** [comment]
Hi Guangchuan,
Yeah, I have uploaded the raw file and have posted the used codes.
Thanks,

**Comment by ajeetmandal** [comment]
I have posted the raw data and the R codes I am using (https://github.com/ajeetmandal/My_ChIP).
Thanks,
Ajeet

**Comment by GuangchuangYu** [comment]
```r
> compKEGG <- compareCluster(geneCluster   = genes,
+ fun           = "enrichKEGG",
+ pvalueCutoff  = 0.05,
+ pAdjustMethod = "BH")
> summary(compKEGG) %>% head
    Cluster       ID                                            Description
1  ARmo\n0M hsa04510                                         Focal adhesion
2  ARmo\n0M hsa05412 Arrhythmogenic right ventricular cardiomyopathy (ARVC)
3 ARmo\n1nM hsa04724                                  Glutamatergic synapse
4 ARmo\n1nM hsa04924                                        Renin secretion
5 ARmo\n1nM hsa04726                                   Serotonergic synapse
6 ARmo\n1nM hsa04921                             Oxytocin signaling pathway
  GeneRatio  BgRatio       pvalue     p.adjust       qvalue
1    16/206 202/7018 2.729657e-04 3.545970e-02 3.445477e-02
2     9/206  74/7018 2.871231e-04 3.545970e-02 3.445477e-02
3    27/575 114/7018 3.083271e-07 8.386496e-05 7.140206e-05
4    18/575  64/7018 2.138373e-06 2.284985e-04 1.945421e-04
5    25/575 112/7018 2.729693e-06 2.284985e-04 1.945421e-04
6    31/575 158/7018 3.360273e-06 2.284985e-04 1.945421e-04
                                                                                                                                                  geneID
1                                                                       596/88/5295/1298/3915/8516/7414/5908/7057/399694/83660/3909/3672/5601/5649/53358
2                                                                                                              88/776/6444/8516/783/27091/1000/1829/3672
3             23236/54407/5530/2900/81539/9455/116443/5321/2904/3760/2917/6505/2892/6506/5332/776/2899/2773/3709/5578/2770/2913/2776/55970/5567/775/2783
4                                                                  23236/5734/5530/154/2977/185/3778/810/2982/5332/776/2773/3709/2770/2776/5567/775/1909
5                             23236/3762/4128/247/3781/351/5321/4129/3760/1644/2562/5332/776/3355/3751/2773/3709/5578/2770/2776/55970/5567/775/2783/3358
6 23236/5530/3762/2977/5997/783/4659/5321/29904/3760/6262/810/2982/4660/5332/776/781/2773/3709/5578/816/1956/2770/54776/55799/817/5295/2776/5567/775/952
  Count
1    16
2     9
3    27
4    18
5    25
6    31
```

KEGG works. 

In your source code, I found that you are using an outdated version of clusterProfiler.

```r
> compGO <- compareCluster(geneCluster   = genes, 
+                          fun           = "enrichGO",
+                          pvalueCutoff  = 0.05, 
+                          pAdjustMethod = "BH")
Error in is(OrgDb, "character") : 
  argument "OrgDb" is missing, with no default
> 
```

In the newest version of `clusterProfiler`, your function call will throw error since you need to specifying `OrgDb` parameter.

Please refer to updated vignettes of both [clusterProfiler](http://www.bioconductor.org/packages/clusterProfiler) and [ChIPseeker](http://www.bioconductor.org/packages/ChIPseeker), and of course you need to update your R (3.3.0) and Bioconductor (3.3).

**Comment by ajeetmandal** [comment]
That was a real help thanks.
I got the updated R and Bioconductor and get the newest version of `clusterProfiler`.
Thanks again.
ajeet
