### ISSUE TITLE
simplify function

### ISSUE THREAD

**Issue by oliverschilling** [GuangchuangYu/clusterProfiler#51]
Hello, 

when using the simplify function I get the following error message:
`Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘simplify’ for signature ‘"enrichResult"’`

What am I missing?

Thanks

Oliver

**Comment by GuangchuangYu** [comment]
see <https://github.com/GuangchuangYu/ggtree/wiki/FAQ#could-not-find-function>

**Comment by Tong-Chen** [comment]
https://github.com/GuangchuangYu/ggtree/wiki/FAQ#could-not-find-function this link is broken

**Comment by GuangchuangYu** [comment]
updated link: <https://guangchuangyu.github.io/ggtree/faq/#could-not-find-function>.
