### ISSUE TITLE
enrichKEGG, readable=TRUE is not working?

### ISSUE THREAD

**Issue by cwu365** [GuangchuangYu/clusterProfiler#52]
Hi, Guangchunag, I am using the your clusterprofiler right now. IT is great.  
Here is a error i can not solve:

> kk<- enrichKEGG(gene=gene,
+                 organism = "hsa",
+                 keyType = "kegg",
+                 pvalueCutoff = 1,
+                 pAdjustMethod = "BH",
+                 qvalueCutoff= 1,
+                 #universe=res.genelist, 
+                 #use_internal_data = T,
+                 readable=TRUE)
Error in enrichKEGG(gene = gene, organism = "hsa", keyType = "kegg", pvalueCutoff = 1,  : 
  unused argument (readable = TRUE)

anysuggestions ?

**Comment by GuangchuangYu** [comment]
` unused argument (readable = TRUE)` this is quite explicitly. `readable` argument is not supported.

see also <http://guangchuangyu.github.io/2016/05/convert-biological-id-with-kegg-api-using-clusterprofiler/>
