### ISSUE TITLE
GSEKEGG

### ISSUE THREAD

**Issue by cwu365** [GuangchuangYu/clusterProfiler#54]
Hi, Guangchuang, 
Thanks for your help last time. 
here is a new error when i use gseKEGG function. 
> kk2 <- gseKEGG(geneList     = geneList,
+                organism     = 'hsa',
+                keyType = "kegg",
+                nPerm        = 1000,
+                minGSSize = 10, 
+                maxGSSize = 500,
+                pvalueCutoff = 1,
+                verbose      = FALSE,
+                seed=TRUE)
Error in data.frame(ID = as.character(gs.name), Description = Description,  : 
  row names contain missing values

enrichKEGG and enrichGO works very well, actually. 

Thanks 

Chun

**Comment by GuangchuangYu** [comment]
follow [the guide](https://github.com/GuangchuangYu/clusterProfiler/blob/master/CONTRIBUTING.md) and post a reproducible example.
