### ISSUE TITLE
question about the "%<>%"?

### ISSUE THREAD

**Issue by wangshisheng** [GuangchuangYu/clusterProfiler#58]
Hello Guangchuang,

I found the character "%<>%" in the groupGO function, could you explain something about it? How could I use it by myself?

Thank you very much.

Best Regards,
Shisheng

**Comment by GuangchuangYu** [comment]
for user question, please post to [Bioconductor support site or biostars](https://guangchuangyu.github.io/clusterProfiler/#feedback).
