### ISSUE TITLE
3.1.5 not building

### ISSUE THREAD

**Issue by LiNk-NY** [GuangchuangYu/clusterProfiler#61]
Hi @GuangchuangYu, 
Your package on SVN is not building (`Revision: 120107`). I get the following error message: 

```
Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object 'build_Anno' not found
```
Could you please correct it and bump the version? 

Thank you.

**Comment by GuangchuangYu** [comment]
I updated `GOSemSim`, `DOSE` and `clusterProfiler` simultaneously. It seems that your issue is due to upgrade `clusterProfiler` before `GOSemSim` and `DOSE`.

**Comment by LiNk-NY** [comment]
If `clusterProfiler` is dependent on your other updates, you should update the fields in `DESCRIPTION` to ensure that the user has the latest dependency (e.g., `Depends: DOSE (>= 2.11.7)`)

**Comment by GuangchuangYu** [comment]
yes, you are right. That's my fault. I will correct it.

**Comment by ustervbo** [comment]
Just upgraded form the Bioc version.

I removed the old packages and ran:

```install.packages("devtools")
library(devtools)

install_github("ctlab/fgsea")
install_github("GuangchuangYu/GOSemSim")
install_github("GuangchuangYu/DOSE")
install_github("GuangchuangYu/clusterProfiler")```

Installed without problems

**Comment by LiNk-NY** [comment]
We're talking about the SVN versions of these packages. You'd install them from `BiocInstaller::biocLite("clusterProfiler")`

**Comment by GuangchuangYu** [comment]
@LiNk-NY FYI, A new version 3.1.6 was committed to BioC.
