### ISSUE TITLE
enrichGO filtering by p.adjust

### ISSUE THREAD

**Issue by guillermomarco** [GuangchuangYu/clusterProfiler#62]
Dear Guangchuang,

I'm looking forward to filter an `enrichGO` object.
I've accomplished filtering GO terms in enrichGO object using `gsfilter`, however I would like also to filter by a minimum `p.adjust` threshold.
I've been looking into docs of **DOSE** and **clusterProfiler** however I didn't find anything to achieve this task. I can filter `enrichGO` object if I transform it into `data.frame` but then I lose all the object functionality.

**Comment by GuangchuangYu** [comment]
you can transform it to data.frame and filter it. then assign the data.frame back to object@result.
