### ISSUE TITLE
when  doing compareCluster for KEGG, how to transfer geneID ENTRIZID to symbol and then save as SVG file  liking for GO analysis with geneID displayed as symbol?

### ISSUE THREAD

**Issue by vagabond12** [GuangchuangYu/clusterProfiler#74]
when  doing compareCluster for KEGG, how to transfer geneID ENTRIZID to symbol and then save as SVG file  liking for GO analysis with geneID displayed as symbol? Thanks

**Comment by GuangchuangYu** [comment]
github issus is for bug report and feature request. 

Please post your question on <http://biostars.org/> next time.

You can use `setReadable` function, see my reply in <https://support.bioconductor.org/p/90508/#90577>.
