### ISSUE TITLE
enrichKegg Description is <NA>

### ISSUE THREAD

**Issue by llrs** [GuangchuangYu/clusterProfiler#77]
In the recent versions of clusterProfiler I have found that all my pathways are NA see:

```r
               ID Description GeneRatio BgRatio       pvalue  p.adjust     qvalue
hsa00603 hsa00603        <NA>      2/20 14/5869 0.0009797338 0.0305606 0.02680754
hsa00511 hsa00511        <NA>      2/20 17/5869 0.0014552666 0.0305606 0.02680754
            geneID Count
hsa00603 2717/3074     2
hsa00511 2519/3074     2
```

Also, have a look at the example, it doesn't return any significant pathway, which may not be what you wanted to show :D

> R version 3.3.2 (2016-10-31)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.2 LTS
> 
> locale:
>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
>  [3] LC_TIME=es_ES.UTF-8        LC_COLLATE=en_US.UTF-8    
>  [5] LC_MONETARY=es_ES.UTF-8    LC_MESSAGES=en_US.UTF-8   
>  [7] LC_PAPER=es_ES.UTF-8       LC_NAME=C                 
>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
> [11] LC_MEASUREMENT=es_ES.UTF-8 LC_IDENTIFICATION=C       
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] BiocInstaller_1.24.0   clusterProfiler_3.2.10 DOSE_3.0.9            
> 
> loaded via a namespace (and not attached):
>  [1] qvalue_2.6.0         gtools_3.5.0         fgsea_1.0.2         
>  [4] reshape2_1.4.2       splines_3.3.2        colorspace_1.3-0    
>  [7] graphite_1.20.1      stats4_3.3.2         hash_2.2.6          
> [10] chron_2.3-47         DBI_0.5-1            BiocParallel_1.8.1  
> [13] rappdirs_0.3.1       BiocGenerics_0.20.0  RColorBrewer_1.1-2  
> [16] gsubfn_0.6-6         KEGG.db_3.2.3        plyr_1.8.4          
> [19] stringr_1.1.0        STRINGdb_1.14.0      munsell_0.4.3       
> [22] GOSemSim_2.0.3       gtable_0.2.0         caTools_1.17.1      
> [25] Biobase_2.34.0       IRanges_2.8.1        parallel_3.3.2      
> [28] AnnotationDbi_1.36.0 proto_1.0.0          Rcpp_0.12.8         
> [31] KernSmooth_2.23-15   reactome.db_1.58.0   scales_0.4.1        
> [34] ReactomePA_1.18.1    gdata_2.17.0         plotrix_3.6-3       
> [37] DO.db_2.9            S4Vectors_0.12.0     graph_1.52.0        
> [40] gplots_3.0.1         gridExtra_2.2.1      fastmatch_1.0-4     
> [43] ggplot2_2.2.0        png_0.1-7            stringi_1.1.2       
> [46] grid_3.3.2           tools_3.3.2          bitops_1.0-6        
> [49] magrittr_1.5         sqldf_0.4-10         lazyeval_0.2.0      
> [52] RCurl_1.95-4.8       tibble_1.2           RSQLite_1.0.0       
> [55] GO.db_3.4.0          tidyr_0.6.0          data.table_1.9.8    
> [58] assertthat_0.1       igraph_1.0.1

**Comment by GuangchuangYu** [comment]
```r
> require(clusterProfiler)
Loading required package: clusterProfiler
Loading required package: DOSE

DOSE v3.0.9  For help: https://guangchuangyu.github.io/DOSE

If you use DOSE in published research, please cite:
Guangchuang Yu, Li-Gen Wang, Guang-Rong Yan, Qing-Yu He. DOSE: an R/Bioconductor package for Disease Ontology Semantic and Enrichment analysis. Bioinformatics 2015, 31(4):608-609

clusterProfiler v3.2.10  For help: https://guangchuangyu.github.io/clusterProfiler

If you use clusterProfiler in published research, please cite:
Guangchuang Yu., Li-Gen Wang, Yanyan Han, Qing-Yu He. clusterProfiler: an R package for comparing biological themes among gene clusters. OMICS: A Journal of Integrative Biology. 2012, 16(5):284-287.
> data(geneList)
> de = names(geneList)
> de = names(geneList)[1:100]
> x = enrichKEGG(de)
> x
#
# over-representation test
#
#...@organism 	 hsa 
#...@ontology 	 KEGG 
#...@keytype 	 kegg 
#...@gene 	 chr [1:100] "4312" "8318" "10874" "55143" "55388" "991" ...
#...pvalues adjusted by 'BH' with cutoff <0.05 
#...3 enriched terms found
'data.frame':	3 obs. of  9 variables:
 $ ID         : chr  "hsa04110" "hsa04114" "hsa04115"
 $ Description: chr  "Cell cycle" "Oocyte meiosis" "p53 signaling pathway"
 $ GeneRatio  : chr  "8/41" "6/41" "4/41"
 $ BgRatio    : chr  "124/7176" "124/7176" "69/7176"
 $ pvalue     : num  3.76e-07 6.46e-05 6.06e-04
 $ p.adjust   : num  3.72e-05 3.20e-03 2.00e-02
 $ qvalue     : num  3.48e-05 2.99e-03 1.87e-02
 $ geneID     : chr  "8318/991/9133/890/983/4085/7272/1111" "991/9133/983/4085/51806/6790" "9133/6241/983/1111"
 $ Count      : int  8 6 4
#...Citation
  Guangchuang Yu, Li-Gen Wang, Yanyan Han and Qing-Yu He.
  clusterProfiler: an R package for comparing biological themes among
  gene clusters. OMICS: A Journal of Integrative Biology
  2012, 16(5):284-287 

```

I can't reproduce your issue, and thanks for pointing out the example.

**Comment by llrs** [comment]
Strange, after three trials I finally could print the description. It might be a problem with my setup... Thanks for your quick response

**Comment by GuangchuangYu** [comment]
and also might be a problem of the KEGG web site.
