### ISSUE TITLE
Plot parameter

### ISSUE THREAD

**Issue by theroseven** [GuangchuangYu/clusterProfiler#80]
Dear Guangchuang,

When using the plot/dotplot function to show the compareClusterResult, is there a parameter to adjust the coordinates labels? For example, I want the xlab to be displayed vertically.

PS,  I don't quite understand when "type = 'dot' and includeAll = TRUE", what does "showCategory" mean?

![image](https://cloud.githubusercontent.com/assets/25194131/22182297/eceb5176-e0dc-11e6-9a0d-2707a28bd81f.png)

As shown in the figure,  I set “showCategory=5” and how to explain multiple category of X3~X5 ? 

Thank you for your help!

Best,
Yuening

**Comment by GuangchuangYu** [comment]
The documentation page, <https://guangchuangyu.github.io/clusterProfiler/documentation/>, is your friend.

For `showCategory`, please refer to the post, <https://guangchuangyu.github.io/2016/11/showcategory-parameter-for-visualizing-comparecluster-output/>.

Suppose `p` is the output of `dotplot`, you can use `p + theme(axis.text.x=element_text(angle=90, hjust=1))` to rotate the `xlab`.

BTW: I prefer using `github` for bug report, if you have further questions, please post them to `Bioconductor` support site or `Biostars`.
