### ISSUE TITLE
Problem when using "plotGOgraph" function

### ISSUE THREAD

**Issue by xinyao120** [GuangchuangYu/clusterProfiler#81]
Hi,
Thank you for your great work!However,when I using "plotGOgraph" function,an error occured,how can I solve it?
Thank you!
LiuYu
[error.txt](https://github.com/GuangchuangYu/clusterProfiler/files/723479/error.txt)

[a_go.txt](https://github.com/GuangchuangYu/clusterProfiler/files/723494/a_go.txt)

**Comment by GuangchuangYu** [comment]
since your result only contains 2 enriched term and `plotGOgraph` try to plot (by default) 10 most significant terms, it throw error for not enough enriched terms to plot.

This has been fixed in devel branch. Currently, you can use `plotGOgraph(go_enrich_cc, firstSigNodes=2)` to solve this issue.
