### ISSUE TITLE
Plotting many clusters

### ISSUE THREAD

**Issue by llrs** [GuangchuangYu/clusterProfiler#83]
### Prerequisites

+ [x] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [x] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [x] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb)) 

When I try to plot several clusters (46) I only get 28 clusters represented (when 18 hadn't any  enriched terms). I don't know if this is due to some internal limitation or the page size.

I am not sure if this depends of clusterProfiler or from DOSE from which it inherits the dotplot function. Apologies in advance because I don't provide the data to reproduce it, but it would be too big. 

```r
library("clusterProfiler")
cGO <- compareCluster(clusters, fun = "enrichGO", ont = "CC",
                        OrgDb = org.Hs.eg.db)
(plot.cGO <- dotplot(cGO))
length(clusters)
# [1] 46
lengths(cGO@geneClusters)
#      turquoise        skyblue3      lightgreen           brown      lightcyan1 
#           2824              49             143             850              38 
#           pink             red            blue    midnightblue             tan 
#            295             437            2755             198             240 
#         orange           black     greenyellow          salmon          yellow 
#            113             305             258             217             800 
#      darkgreen     lightyellow         sienna3     darkorange2           green 
#            127             136              57              30             726 
#     orangered4          purple   darkturquoise       royalblue         skyblue 
#             45             253             118             135              85 
#      steelblue      darkorange lightsteelblue1            grey   paleturquoise 
#             78             100              41              58              72 
#       darkgrey         darkred           white          grey60       lightcyan 
#            114             129              98             167             188 
# darkolivegreen         magenta   mediumpurple3     darkmagenta     floralwhite 
#             70             274              43              65              31 
#    saddlebrown            cyan           plum1           ivory          violet 
#             81             202              48              32              71 
#    yellowgreen 
#             52 
```

**Comment by GuangchuangYu** [comment]
making a simple reproducible example is not that difficult.

```
require(clusterProfiler)
data(geneList)
i = round(seq(1, length(geneList)-1, length.out=51))
cls = lapply(1:50, function(j) names(geneList)[i[j]:i[j+1]])
names(cls) = paste0("X", 1:50)

## using DO to speed up this step
x = compareCluster(cls, fun = "enrichDO",  pvalueCutoff=1, qvalueCutoff=1)
dotplot(x)
```

It indeed works.

![screen shot 2017-03-17 at 12 21 59 pm](https://cloud.githubusercontent.com/assets/626539/24028738/605d0326-0b0c-11e7-96c1-9cdcf763d467.png)

**Comment by llrs** [comment]
Maybe the bug/problem is related to not having all the clusters enriched in the same terms but in several different terms. I will update the issue if I manage to make a shorter reproducible example.
