### ISSUE TITLE
Installing clusterProfiler on Debian :   libpng16.so.16: cannot open shared object file

### ISSUE THREAD

**Issue by LucoLab** [GuangchuangYu/clusterProfiler#86]
> biocLite("clusterProfiler")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.2 (BiocInstaller 1.20.3), R 3.3.3 (2017-03-06).
Installing package(s) ‘clusterProfiler’
also installing the dependencies ‘png’, ‘KEGGREST’

trying URL 'https://cran.rstudio.com/src/contrib/png_0.1-7.tar.gz'
Content type 'unknown' length 24990 bytes (24 KB)
downloaded 24 KB

trying URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/KEGGREST_1.10.1.tar.gz'
Content type 'unknown' length 23812 bytes (23 KB)
downloaded 23 KB

trying URL 'https://bioconductor.org/packages/3.2/bioc/src/contrib/clusterProfiler_2.4.3.tar.gz'
Content type 'unknown' length 3465952 bytes (3.3 MB)
downloaded 3.3 MB

During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
* installing *source* package ‘png’ ...
** package ‘png’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      `libpng-config --cflags` -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
gcc -std=gnu99 -I/usr/share/R/include -DNDEBUG      `libpng-config --cflags` -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c write.c -o write.o
gcc -std=gnu99 -shared -L/usr/lib/R/lib -Wl,-z,relro -o png.so read.o write.o -L/home/jean-philippe.villemin/bin/anaconda3/lib -lpng16 -lm -lz -lm -L/usr/lib/R/lib -lR
installing to /home/jean-philippe.villemin/R/x86_64-pc-linux-gnu-library/3.2/png/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/jean-philippe.villemin/R/x86_64-pc-linux-gnu-library/3.2/png/libs/png.so':
  libpng16.so.16: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jean-philippe.villemin/R/x86_64-pc-linux-gnu-library/3.2/png’
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
ERROR: dependency ‘png’ is not available for package ‘KEGGREST’
* removing ‘/home/jean-philippe.villemin/R/x86_64-pc-linux-gnu-library/3.2/KEGGREST’
During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
ERROR: dependency ‘KEGGREST’ is not available for package ‘clusterProfiler’
* removing ‘/home/jean-philippe.villemin/R/x86_64-pc-linux-gnu-library/3.2/clusterProfiler’

The downloaded source packages are in
	‘/tmp/RtmptIHYCg/downloaded_packages’
Old packages: 'boot', 'foreign', 'lattice', 'Matrix', 'survival', 'assertthat',
  'curl', 'DBI', 'Hmisc', 'htmltools', 'jsonlite', 'markdown', 'matrixStats',
  'memoise', 'Rcpp', 'RcppArmadillo', 'SparseM', 'stringi', 'tibble',
  'viridis', 'XML', 'Matrix', 'survival', 'HilbertVis', 'boot', 'cluster',
  'foreign', 'lattice', 'MASS', 'Matrix', 'mgcv', 'rpart', 'survival'
Update all/some/none? [a/s/n]: q
Update all/some/none? [a/s/n]: n
Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘png’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘KEGGREST’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘clusterProfiler’ had non-zero exit status

**Comment by GuangchuangYu** [comment]
the version you try to install was updated. KEGGREST is not depended by current release of [clusterProfiler](https://bioconductor.org/packages/release/bioc/html/clusterProfiler.html).
