### ISSUE TITLE
Feature Request: KEGG pathway Enrichment that accept background and ensembl gene id as an input

### ISSUE THREAD

**Issue by poryaparvizi** [GuangchuangYu/clusterProfiler#87]
Dear Guangchuang,

I am using clusterProfiler in Kegg pathway enrichment analysis, it is useful and nice. I am looking for a function which accept background and has ability to deal with Ensembl gene ID. 

In a function enrichDAVID it can takes ensembl gene id as an input format, but not allows to enter background.
`enrichDAVID(gene = gene, idType="ENSEMBL_GENE_ID", annotation="KEGG_PATHWAY", species= "hsa")`

Other command enrichKEGG has a background input but only takes entrez gene id,
`enrichKEGG(gene, organism = "hsa", keyType = "kegg", universe)`

I have tried to convert my ensembl gene IDs to entrez gene id, but some ensembl gene IDs represent more than one entrez gene ID. 
I downloaded KEGG pathway dataset to apply fisher exact test. however, genes are in entrez ID and i am still dont know how to convert.

**Comment by GuangchuangYu** [comment]
For ID conversion, please refer to vignette and ID conversion in [document page](https://guangchuangyu.github.io/clusterProfiler/documentation/).

Background list for DAVID is now supported, see the following screenshot:

![screenshot 2017-05-16 07 32 44](https://cloud.githubusercontent.com/assets/626539/26083728/f7f16552-3a09-11e7-9177-13db9b9a241a.png)

**Comment by poryaparvizi** [comment]
I dont know why it doesnt happen to you but i tried same example and i get "Read timed out" error when i enter background. 
I change the time out interval but nothing changed.

`david= DAVIDWebService$new()`
`setTimeOut(david, 50000)`

**Comment by GuangchuangYu** [comment]
Then you should report to `RDAVIDWebService` package maintainer.
