### ISSUE TITLE
how to use bitr

### ISSUE THREAD

**Issue by Liangsiyuan123** [GuangchuangYu/clusterProfiler#89]
### Prerequisites

which db should i fill in the blank of  OrgDb ?
bitr(geneID, fromType, toType, OrgDb, drop = TRUE)

**Comment by GuangchuangYu** [comment]
<https://bioconductor.org/packages/devel/bioc/vignettes/clusterProfiler/inst/doc/clusterProfiler.html#bitr-biological-id-translator>.

**Comment by Liangsiyuan123** [comment]
thanks, Mr.Y
