### ISSUE TITLE
merge two enrichGO results from two org.db

### ISSUE THREAD

**Issue by NMB32** [GuangchuangYu/clusterProfiler#90]
I found two org.db when I typed following commands.
>library(AnnotationHub)
>hub <- AnnotationHub()
>query(hub, "Glycine max") 

I am trying to merge two enrichGO results from two org.db, but I could not do.
I would like to perform plotGOgraph and enrichMap with the merged result.
Please tell me how to merge two two enrichGO results from two org.db.

**Comment by GuangchuangYu** [comment]
```r
> query(hub, "Glycine max")
AnnotationHub with 2 records
# snapshotDate(): 2017-04-25
# $dataprovider: Inparanoid8, ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/
# $species: Glycine max
# $rdataclass: Inparanoid8Db, OrgDb
# additional mcols(): taxonomyid, genome, description,
#   coordinate_1_based, maintainer, rdatadateadded, preparerclass, tags,
#   rdatapath, sourceurl, sourcetype
# retrieve records with, e.g., 'object[["AH10511"]]'

            title
  AH10511 | hom.Glycine_max.inp8.sqlite
  AH55734 | org.Glycine_max.eg.sqlite
```

What you need is the second one, `org.Glycine_max.eg.sqlite`, which is the `OrgDb`.

**Comment by NMB32** [comment]
Thank you for replying my question. 

I could not find AH55734, but found AH13355 and AH48007.
The snapshotDate of AH13355 and AH48007 is 2017-06-08, newer than AH55734.
           title                      
  AH10511 | hom.Glycine_max.inp8.sqlite
  AH13355 | org.Glycine_max.eg.sqlite  
  AH48007 | org.Glycine_max.eg.sqlite  

AnnotationHub with 3 records
# snapshotDate(): 2017-06-08 
# $dataprovider: Inparanoid8, NCBI, ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/
# $species: Glycine max
# $rdataclass: OrgDb, Inparanoid8Db
# additional mcols(): taxonomyid, genome, description, tags, sourceurl, sourcetype 
# retrieve records with, e.g., 'object[["AH10511"]]'
