### ISSUE TITLE
enrichGO error with setReadable (Error in .testForValidCols(x, cols))

### ISSUE THREAD

**Issue by MarisaMiller** [GuangchuangYu/clusterProfiler#91]
Hi Guangchuang,
I have been searching all around the internet to solve this issue to no avail. I am using clusterProfiler with a custom OrgDB but keep running into the same error. Here is how I am running the analysis (as an initial test I am just using the same gene list as input and background):

Here, I just duplicated the GID to a LOCUS column to build the orgDB, hence why the names are the same.

```
> head(sd80_genes)
          GID       LOCUS
1 PCASD_00001 PCASD_00001
2 PCASD_00002 PCASD_00002
3 PCASD_00003 PCASD_00003
4 PCASD_00004 PCASD_00004
5 PCASD_00005 PCASD_00005
6 PCASD_00006 PCASD_00006
```

Here is the test gene list:

```
> head(sd80_effector_P)
        LOCUS
1 PCASD_11070
2 PCASD_24046
3 PCASD_06119
4 PCASD_04126
5 PCASD_05688
6 PCASD_13004
```
This command works below with readable = FALSE. I see a large enrichResult of 3.1 Mb is created.

```
sd80_effector_P = read.csv("sd80_effectors_P_list", header=TRUE)
sd80_universe <- sd80_genes$LOCUS

sd80_ego_BP <- enrichGO(gene          = sd80_effector_P$LOCUS,
                universe      = sd80_universe,
                OrgDb         = org.PcoronataAvenae12SD80.eg.db,
                keytype = "LOCUS",
                ont           = "BP",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.01,
                qvalueCutoff  = 0.05,
                readable      = FALSE)
```

But, if I changed readable to TRUE or use this command `sd80_ego_BP <- setReadable(sd80_ego_BP, org.PcoronataAvenae12SD80.eg.db, keytype = "LOCUS")`, I get the following error:

```
Error in .testForValidCols(x, cols) : 
  Invalid columns: SYMBOL. Please use the columns method to see a listing of valid arguments.
```

If I use the columns method it looks like the column name should be valid:
```
> columns(org.PcoronataAvenae12SD80.eg.db)
[1] "EVIDENCE"    "EVIDENCEALL" "GID"         "GO"          "GOALL"       "LOCUS"       "ONTOLOGY"    "ONTOLOGYALL"
```
Any ideas about this issue? I can't tell if this is a bug or another issue, so any advice you have would be greatly appreciated!

Thanks,
Marisa

Here's my sessionInfo():

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.5

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] org.PcoronataAvenae12SD80.eg.db_0.1 org.PcoronataAvenae12NC29.eg.db_0.1 AnnotationDbi_1.38.1               
[4] IRanges_2.10.2                      S4Vectors_0.14.3                    Biobase_2.36.2                     
[7] BiocGenerics_0.22.0                 clusterProfiler_3.4.4               DOSE_3.2.0                         

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11        compiler_3.4.0      plyr_1.8.4          tools_3.4.0         digest_0.6.12       bit_1.1-12         
 [7] RSQLite_2.0         memoise_1.1.0       tibble_1.3.3        gtable_0.2.0        pkgconfig_2.0.1     rlang_0.1.1        
[13] fastmatch_1.1-0     igraph_1.0.1        DBI_0.7             rvcheck_0.0.8       fgsea_1.2.1         gridExtra_2.2.1    
[19] stringr_1.2.0       bit64_0.9-7         grid_3.4.0          qvalue_2.8.0        data.table_1.10.4   BiocParallel_1.10.1
[25] GOSemSim_2.2.0      tidyr_0.6.3         GO.db_3.4.1         DO.db_2.9           ggplot2_2.2.1       reshape2_1.4.2     
[31] blob_1.1.0          magrittr_1.5        splines_3.4.0       scales_0.4.1        colorspace_1.3-2    stringi_1.1.5      
[37] lazyeval_0.2.0      munsell_0.4.3     
```

**Comment by MarisaMiller** [comment]
By the way, I see the same issue in [this blog post](https://shiring.github.io/genome/2017/01/05/homologous_genes_part3_post), but they never solved the issue.

**Comment by GuangchuangYu** [comment]
This is of course not a bug. The `readable` parameter is to convert the input geneID to gene Symbol and your customized OrgDb doesn't have that information.

I think throwing error is not a good idea, instead I will change it to just throw warning message as show below in next release and return the result with original geneID.

```
Warning message:
Fail to convert input geneID to SYMBOL since no SYMBOL information available in the provided OrgDb...
```

**Comment by MarisaMiller** [comment]
Hi Guangchuang,

Thanks so much for the helpful reply. It's good to know it's not an issue and I can just ignore that error message. I think I misunderstood the readable parameter, and now I understand it's not needed for my analysis with a custom OrgDB.

I do have a couple more questions regarding interpretation. For the result from above (`sd80_ego_BP`):
```
> as.data.frame(sd80_ego_BP)
[1] ID          Description GeneRatio   BgRatio     pvalue      p.adjust    qvalue      geneID      Count      
<0 rows> (or 0-length row.names)
```
does this indicate that there are no significant enrichments at for that significance level for that ontology? It seems strange that it's just empty, but I was wondering if non-significant results are not reported.

I tried gseGO as well to see if it works, and am getting a keytype error here:
 ```
sd80_gse_BP <- gseGO(geneList = sd80_effector_P$LOCUS,
                     ont = "BP",
                     OrgDb = org.PcoronataAvenae12SD80.eg.db,
                     keytype = "LOCUS",
                     verbose = F)
```
```
Error in gseGO(geneList = sd80_effector_P$LOCUS, ont = "BP", OrgDb = org.PcoronataAvenae12SD80.eg.db,  : 
  unused argument (keytype = "LOCUS")
```
Thanks again for the help, and please let me know if you need more information.

**Comment by GuangchuangYu** [comment]
```
 unused argument (keytype = "LOCUS")
```

This indicates that you are using the wrong argument. 

You can use `args` to access the parameter list:

```r
> args(gseGO)
function (geneList, ont = "BP", OrgDb, keyType = "ENTREZID",
    exponent = 1, nPerm = 1000, minGSSize = 10, maxGSSize = 500,
    pvalueCutoff = 0.05, pAdjustMethod = "BH", verbose = TRUE,
    seed = FALSE, by = "fgsea")
```


This is totally my fault. I will change it all to `keyType` in future release for consistent.

**Comment by MarisaMiller** [comment]
Ahh, that makes sense! I changed it and it seems to be working, but of course there's a problem with my geneList that I'll try to fix.
```
Error in GSEA_internal(geneList = geneList, exponent = exponent, nPerm = nPerm,  : 
  geneList should be a decreasing sorted vector...
```

Also, I figured out that yes indeed the enrichGO result is "empty" when no significant results are found. I tried the MF and CC ont methods, keeping all else the same, and got results in those cases.

Thank you!!

**Comment by GuangchuangYu** [comment]
You can always check with larger pvalueCutoff and qvalueCutoff.

For your `geneList` issue, you input, `geneList = sd80_effector_P$LOCUS` is wrong. The GSEA algorithm using all genes sorted by numerical values (e.g. expression value, fold change etc.). 


see <https://github.com/GuangchuangYu/DOSE/wiki/how-to-prepare-your-own-geneList> for explanation of preparing your data.
