### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by lcolladotor** [GuangchuangYu/clusterProfiler#93]
Hi,

Could you bump the version of the package? I saw that you edited the `keytype` argument in `enrichGO()` and is now called `keyType`. You did it in one of the latest commits but didn't bump the version of the package since then: https://github.com/GuangchuangYu/clusterProfiler/commit/6dd756352d982c38fa28a0769726bd7ab31e2fd2. This meant that the Bioc-devel version of `clusterProfiler` I had (3.5.4) installed from the latest binary for Mac could not reproduce a bug I was seeing on the single package builder at https://github.com/Bioconductor/Contributions/issues/421. It took me a while to figure out what was going on and that I needed to install the package from source on my Mac if I wanted to reproduce the issue.

If you bump the version of the package, new binaries should be built matching your latest commits. As it stands right now, 2 people could have version 3.5.4 installed (based on binaries and based on source) and only 1 of them could use the code without errors.

Best,
Leonardo

**Comment by GuangchuangYu** [comment]
v = 3.5.5 already on both github & bioc_git.

thanks!

**Comment by lcolladotor** [comment]
Awesome, thanks!

**Comment by lcolladotor** [comment]
Hi again,

It looks like the latest version didn't make it to Bioconductor. At https://github.com/Bioconductor-mirror/clusterProfiler/blob/master/DESCRIPTION#L5and https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/clusterProfiler/DESCRIPTION I still see version 3.5.4 instead of 3.5.5.

Best,
Leo

**Comment by lshep** [comment]
In order to be updated on Bioc devel  it has to be updated in the svn repo. See the link here for how to do that: http://bioconductor.org/developers/how-to/git-mirrors/

**Comment by GuangchuangYu** [comment]
I do push it to bioc-git:

```
~/g/others ❯❯❯ git clone https://git.bioconductor.org/packages/clusterProfiler.git                                                                          
Cloning into 'clusterProfiler'...
remote: Counting objects: 4544, done.
remote: Compressing objects: 100% (1678/1678), done.
remote: Total 4544 (delta 3209), reused 3826 (delta 2715)
Receiving objects: 100% (4544/4544), 10.45 MiB | 2.96 MiB/s, done.
Resolving deltas: 100% (3209/3209), done.
~/g/others ❯❯❯ cat clusterProfiler/DESCRIPTION|grep Version
Version: 3.5.5
```

@lshep You mean I also need to push it to svn server? That's horrible. BioC should take that responsibility to sync git and svn as they propose to transit to git.

**Comment by GuangchuangYu** [comment]
@lcolladotor Now on Bioc svn 😿

**Comment by lcolladotor** [comment]
Thanks!
