### ISSUE TITLE
How many pathways in KEGG database?

### ISSUE THREAD

**Issue by eshinesimida** [GuangchuangYu/clusterProfiler#95]
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/clusterprofiler/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/clusterprofiler/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `clusterProfiler`

**Comment by GuangchuangYu** [comment]
it depends on which species and the number is changing as time goes on.

**Comment by eshinesimida** [comment]
Thank you

**Comment by eshinesimida** [comment]
Are you in Guangzhou now?

**Comment by GuangchuangYu** [comment]
want to buy me a beer?

**Comment by eshinesimida** [comment]
Yes

**Comment by GuangchuangYu** [comment]
:smiley:

**Comment by eshinesimida** [comment]
we are able to talk more each other in guangzhou
