### ISSUE TITLE
"Error in is(OrgDb, "character")" occured in enrichGO

### ISSUE THREAD

**Issue by silvewheat** [GuangchuangYu/clusterProfiler#96]
Hi Guangchuang,
      When I use enrichGO function, an error occured.
      My command is:
`ego2 <- enrichGO(gene = genedf[,'V1'], OrgDb = org.Hs.eg.db,  keytype = 'ncbi-geneid', pAdjustMethod = 'BH', readable = True, pvalueCutoff=0.01)`
      error message is:
`Error in is(OrgDb, "character") : 找不到对象'org.Hs.eg.db'`
      and I try to brackets to org.Hs.eg.db, but error also occured same.

![image](https://user-images.githubusercontent.com/19344997/28762244-6e7e3ef2-75e7-11e7-9114-86ca61df8275.png)

      Should I do some prebuild work about the GO database?

**Comment by GuangchuangYu** [comment]
you need to quote the OrgDb or load it before passing to enrichGO.

**Comment by silvewheat** [comment]
Thanks for your response,
       I try to quote it, but it's still don't work. Just like picture below:
![image](https://user-images.githubusercontent.com/19344997/28765548-e94ed54a-75fd-11e7-9c41-5b6f5936a24b.png)
![image](https://user-images.githubusercontent.com/19344997/28766482-4b5a265a-7602-11e7-8e66-66d0b5d3de2b.png)

     And, how can i load it before use the enrichGO?

**Comment by GuangchuangYu** [comment]
then you need to install the package via `biocLite("org.Hs.eg.db")`.

**Comment by silvewheat** [comment]
Thank you!
After installed, it works now!
