### ISSUE TITLE
Does enrichKEGG and enrichDO support mouse species?

### ISSUE THREAD

**Issue by zhengwang1** [GuangchuangYu/clusterProfiler#97]
Hi, I prefer using your package to do enrichment comparison. But I met some unknown problem as follow:
compareCluster(Entrez~group,data=mydf,fun = "enrichKEGG",OrgDb="org.Mm.eg.db")
Error in fun(i, ...) : unused argument (OrgDb = "org.Mm.eg.db")
Does enrichKEGG and enrichDO support mouse species? And how to download the latest KEGG database?

Thank you very much!

Zheng

**Comment by GuangchuangYu** [comment]
Please read the document of `enrichKEGG` and `enrichDO`.
