### ISSUE TITLE
unused argument of OrgDb

### ISSUE THREAD

**Issue by theomarker** [GuangchuangYu/clusterProfiler#98]
Hi guangchuang,

Thanks for your great tool.
I met a problem with the argument OrgDb. I follow your instruction on guide.
here is my command and the problem:
library(clusterProfiler)
library(org.Hs.eg.db)
x <- c("GPX3",  "GLRX",   "LBP",   "CRYAB", "DEFB1", "HCLS1",   "SOD2",   "HSPA2",
       "ORM1",  "IGFBP1", "PTHLH", "GPC3",  "IGFBP3","TOB1",    "MITF",   "NDRG1",
       "NR1H4", "FGFR3",  "PVR",   "IL6",   "PTPRM", "ERBB2",   "NID2",   "LAMB1",
       "COMP",  "PLS3",   "MCAM",  "SPP1",  "LAMC1", "COL4A2",  "COL4A1", "MYOC",
       "ANXA4", "TFPI2",  "CST6",  "SLPI",  "TIMP2", "CPM",     "GGT1",   "NNMT",
       "MAL",   "EEF1A2", "HGD",   "TCN2",  "CDA",   "PCCA",    "CRYM",   "PDXK",
       "STC1",  "WARS",  "HMOX1", "FXYD2", "RBP4",   "SLC6A12", "KDELR3", "ITM2B")
eg = bitr(x, fromType="SYMBOL", toType="ENTREZID", OrgDb="org.Hs.eg.db")
**Error in bitr(x, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = "org.Hs.eg.db") : 
  unused argument (OrgDb = "org.Hs.eg.db")**

How this happened? It works on another laptop.
And I also updated my R version. Can you give me any suggestions?

Thanks!
theomarker

**Comment by GuangchuangYu** [comment]
as you ignore [my message](https://github.com/GuangchuangYu/clusterProfiler/issues/new), I will ignore your question.
